#%RAML 1.0 Library

types:
  IOTBlastnConfig:        !include IOTBlastnConfig.raml
  IOTBlastnTask:          !include IOTBlastnTask.raml
  IOTBlastnScoringMatrix: !include IOTBlastnScoringMatrix.raml
