#%RAML 1.0 DataType

uses:
  blastp: ../blastp/index.raml
  blast:  ../blast/index.raml
  ext:    index.raml
  com:    ../blast-common/index.raml

type: blast.InputBlastConfig
discriminatorValue: tblastn
additionalProperties: false
properties:

  task?:
    description: |
      Default value: `tblastn`
    type: ext.InputTBlastnTask

  wordSize?:
    description: |
      Word size for initial match. Valid word sizes are 2-7.

      Default value by task:

      | Task           | Value |
      |----------------|-------|
      | `tblastn`      | 3     |
      | `tblastn-fast` | 6     |

      Applies to task(s): all
    type: integer
    format: int8
    minimum: 2
    maximum: 7

  gapOpen?:
    description: |
      Cost to open a gap.

      Applies to task(s): all
    type: integer
    format: int8
    default: 11
    minimum: 1

  gapExtend?:
    description: |
      Cost to extend a gap.

      Applies to task(s): all
    type: integer
    format: int8
    minimum: 1
    default: 1

  matrix?:
    description: |
      Scoring matrix name.

      Applies to task(s): all

      Default value: `BLOSUM62`
    type: com.InputBlastScoringMatrix

  threshold?:
    description: |
      Minimum score to add a word to the BLAST lookup table.

      Default value by task:

      | Task           | Value |
      |----------------|-------|
      | `tblastn`      | 13    |
      | `tblastn-fast` | 21    |

      Applies to task(s): all
    type: integer
    format: int8
    minimum: 1

  seg?:
    description: |
      Filter query sequence with SEG.

      Applies to task(s): all
    type: com.InputBlastSegMask
    default:
      enabled: true
      window: 12
      locut: 2.2
      hicut: 2.5

  softMasking?:
    description: |
      Apply filtering locations as soft masks (i.e., only for finding initial
      matches).

      Applies to task(s): all
    type: boolean
    default: false

  lcaseMasking?:
    description: |
      Use lower case filtering in query and subject sequence(s).

      Applies to task(s): all
    type: boolean
    default: false

  dbSoftMask?:
    description: |
      Filtering algorithm ID to apply to the BLAST database as soft mask (i.e.,
      only for finding initial matches).

      Applies to task(s): all
    type: integer
    format: int64

  dbHardMask?:
    description: |
      Filtering algorithm ID to apply to the BLAST database as hard mask (i.e.,
      sequence is masked for all phases of search).

      Applies to task(s): all
    type: integer
    format: int64

  xdropGapFinal?:
    description: |
      Heuristic value (in bits) for final gapped alignment.

      Applies to task(s): all
    type: number
    format: double
    default: 25.0

  windowSize?:
    description: |
      Multiple hits window size, use 0 to specify 1-hit algorithm.

      Applies to task(s): all
    type: integer
    format: int16
    minimum: 0
    default: 40

  dbGenCode:
    description: |
      Genetic code to translate subject sequences, see
      ftp://ftp.ncbi.nih.gov/entrez/misc/data/gc.prt

      Applies to task(s): all
    type: integer
    format: int8
    default: 1
    minimum: 1

  maxIntronLength:
    description: |
      Length of the largest intron allowed in a translated nucleotide sequence
      when linking multiple distinct alignments (a negative value disables
      linking).

      Applies to task(s): all
    type: integer
    default: 0
    format: int32

  compBasedStats?:
    description: |
      Use composition-based statistics.

      Applies to task(s): all

      Default value: `conditional-comp-based-score-adjustment`
    type: com.InputBlastCompBasedStats
