#%RAML 1.0 DataType

description: |
   | Task           | Use Case                                                 |
   |----------------|----------------------------------------------------------|
   | `blastx`       | for standard translated nucleotide-protein comparison    |
   | `blastx-fast`  | a faster version that uses a larger word-size based on https://www.ncbi.nlm.nih.gov/pubmed/17921491 |
type: string
enum:
  - blastx
  - blastx-fast
