version: '3.5'

networks:
  monitoring-ext:
    external: true
  traefik:

services:
  traefik:
    image: traefik:2.2
    command:
    - --api.dashboard=true
    - --api.debug=true
    - --providers.docker=true
    - --entrypoints.web.address=:80
    - --entrypoints.websecure.address=:443
    - --entrypoints.local.address=:8443
    ports:
    - 80:80
    - 443:443
    - "127.0.0.1:8443:8443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.http.routers.api.rule: Host(`${TRAEFIK_DOMAIN:-traefik.local.apidb.org}`)
      traefik.http.routers.api.entrypoints: local
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.tls: true
    networks:
    - traefik

  queue-db:
    build:
      dockerfile: ../docker-queue-db/Dockerfile
      context: ../docker-queue-db
    ports:
    - "5432:5432"

  queue:
    ports:
    - "9002:15672"

  minio:
    image: minio/minio
    command: server --console-address ':9001' /data
    ports:
    - "9000:9000"
    - "9001:9001"
    environment:
      MINIO_ROOT_USER:     ${S3_ACCESS_TOKEN:?}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:?}
    networks:
    - internal

  minio-create-buckets:
    image: minio/mc
    depends_on:
    - minio
    entrypoint: >
      /bin/sh -c "
      sleep 1;
      /usr/bin/mc alias set minioc http://minio:9000 ${S3_ACCESS_TOKEN:?} ${S3_SECRET_KEY:?};
      /usr/bin/mc mb minioc/${QUERY_SERVICE_S3_BUCKET:?};
      /usr/bin/mc mb minioc/${REPORT_SERVICE_S3_BUCKET:?};
      /usr/bin/mc policy set public minioc/${QUERY_SERVICE_S3_BUCKET:?};
      /usr/bin/mc policy set public minioc/${REPORT_SERVICE_S3_BUCKET:?};
      exit 0;
      "
    networks:
    - internal

  query-service:
    build:
      dockerfile: service-query/Dockerfile
      context: ..
    ports:
    - "8080:80"
    depends_on:
    - minio
    - queue
    - queue-db

  report-service:
    build:
      dockerfile: service-report/Dockerfile
      context: ..
    ports:
    - "8081:80"
    depends_on:
    - minio
    - queue
    - queue-db
    - query-service
