= blast-types
:source-highlighter: highlightjs
:toc: preamble
:lib-version: 8.2.0

image:https://img.shields.io/github/license/veupathdb/service-multi-blast[GitHub]
image:https://img.shields.io/badge/docs-dokka-green[title="Dokka Docs", link="https://veupathdb.github.io/service-multi-blast/dokka/blast-types/"]
image:https://img.shields.io/badge/version-{lib-version}-blue[link="https://github.com/VEuPathDB/lib-jvm-blast/packages/1359582"]

Library for parsing, serializing, and validating JSON BLAST+ cli configs.

Configs may be constructed or parsed from JSON and written out to several
formats including a CLI call string.


== Import

.build.gradle.kts
[source, kotlin, subs="verbatim,attributes"]
----
  implementation("org.veupathdb.lib:blast-types:{lib-version}")
----

.build.gradle
[source, groovy, subs="verbatim,attributes"]
----
  implementation "org.veupathdb.lib:blast-types:{lib-version}"
----

.pom.xml
[source, xml, subs="verbatim,attributes"]
----
        <dependency>
          <groupId>org.veupathdb.lib</groupId>
          <artifactId>blast-types</artifactId>
          <version>{lib-version}</version>
        </dependency>
----

== Compatibility

[%header]
|===
| Lib Version | BLAST+ Version | JDK Version
| 6.x.x       | 2.11.0+        | 16+
| 7.x.x       | 2.13.0+        | 17+
| 8.x.x       | 2.13.0+        | 8+
|===

== Usage

.Building a CLI Command
[source, kotlin]
----
val config = Blast.blastn {
  task(BlastNTaskType.DiscontiguousMegablast)
  queryFile("my-query.txt")
  dbFiles("my-blast-db")
}

config.toCliString() == "blastn -task 'dc-megablast' -query 'my-query.txt' -db 'my-blast-db'"
----


.Serializing to JSON
[source, kotlin]
----
val config = Blast.blastp {
  task = BlastPTask(BlastPTaskType.BlastPFast)
  queryFile("my-query.txt")
  dbFiles("my-blast-db-1", "my-blast-db-2")
}


config.toJson() == """
{
  "tool": "blastp",
  "-query": "my-query.txt",
  "-db": [
    "my-blast-db-1",
    "my-blast-db-2"
  ],
  "-task": "blastp-fast"
}
"""
----


.Deserializing from JSON
[source, kotlin]
----
val jackson   = ObjectMapper()
val inputJson = jackson.readTree("""
{
  "tool"   : "blastx",
  "-task"  : "blastx-fast",
  "-query" : "my-query.txt",
  "-db"    : [ "my-blast-db" ]
}
""") as ObjectNode

val config = Blast.blastx(inputJson) // or Blast.of(inputJson) if the tool is unknown.

require(config.task.value == BlastXTaskType.BlastXFast)
require(config.queryFile.file == "my-query.txt")
require(config.dbFile.files[0] == "my-blast-db")
----

== Examples

link:examples/printing-help/[printing-help]::
A simple example that calls `blastn -help` to demonstrate building a basic
BLAST+ CLI call.

== Default Values

This library knows all the documented default values for all  flags for each
BLAST+ tool, and will omit those values from serialized forms.  This is done to
keep the serialized form of each config down to the bare minimum as the BLAST+
tools have a large number of flags and options.


.Setting Default Values
[source, kotlin]
----
val config = Blast.deltablast {
  seg = SegDelta.no()
  gapTrigger(22.0)
  compBasedStats(CompBasedStatsDeltaValue.CompBasedStats)
}

require(config.toCliString() == "deltablast")
----


== Validation


=== Field Level Validation

Each field that has a documented set or range of valid values validates the set
value on construction, preventing an invalid flag being used when building a
BLAST+ tool configuration.

If an invalid value is used when constructing a field, an
`IllegalArgumentException` will be thrown.


[source, kotlin]
----
val field = LineLength(-1) // Throws an exception
----


=== Config Level Validation

In addition to the field level validation, whole configs come with a `validate`
method that builds a list of errors for flags that are incompatible with one
another or require an additional flag that is missing.

This validation method returns a `Map` of all the errors encountered keyed on
the name of the relevant flag.

[source, kotlin]
----
val config = Blast.blastFormatter {
  archive("some-archive")
  rid("some-request-id")
}

val errors = config.validate()

errors.toJson() == """
{
  "-archive" : [ "Incompatible with -rid" ],
  "-rid"     : [ "Incompatible with -archive" ]
}
"""
----

== Release Notes

[cols="1h,11a"]
|===
| v8.2.0
| * Adds `clone()` methods to all the BLAST+ configuration types that return a
new copy of the config instance with the same field values.

| v8.1.2
| * Fixes issue with expect value validation.

| v8.1.1
| * Fixes issue with deserializing the -seg field from JSON.

| v8.1.0
| * Adds convenience methods for all properties that allow setting the
properties using a raw type rather than a field wrapper type.
* Adds blast config type constructors that accept builder callbacks.

| v8.0.1
| * Added missing `@JvmStatic` annotations for easier interop with plain Java.

| v8.0.0
| * Re-release of version 7.0.0 targeting JDK 8 for wider usability.
|===
