#%RAML 1.0 Library

uses:
  base: ./blast/blast-cli.raml

types:
  QueryJobRequest:
    displayName: Query Job Request
    type: object
    additionalProperties: false
    properties:
      jobConfig:
        displayName: Job Config
        description: Job Configuration.
        type: QueryJobConfig
      blastConfig:
        displayName: Blast Tool Config
        description: |
          Blast Tool Configuration.
          
          Implemented by one of:
          
          - [BlastNConfig](#type:lib.BlastNConfig)
          - [BlastPConfig](#type:lib.BlastPConfig)
          - [BlastXConfig](#type:lib.BlastXConfig)
          - [DeltaBlastConfig](#type:lib.DeltaBlastConfig)
          - [PSIBlastConfig](#type:lib.PSIBlastConfig)
          - [RPSBlastConfig](#type:lib.RPSBlastConfig)
          - [RPSTBlastNConfig](#type:lib.RPSTBlastNConfig)
          - [TBlastNConfig](#type:lib.TBlastNConfig)
          - [TBlastXConfig](#type:lib.TBlastXConfig)
        type: base.BlastQueryConfig
      meta:
        displayName: User Metadata
        type: QueryJobRequestMeta

  QueryJobConfig:
    type: object
    additionalProperties: false
    properties:
      site:
        displayName: Target Site
        type: TargetSite
      targets:
        displayName: Query Targets
        type: array
        items:
          type: QueryJobTarget
        minItems: 1
      query:
        displayName: Blast Query
        description: |
          Inline query definition.
          
          This field is to be used for non-file-upload blast queries.
          
          If this field is not set, a query file must be uploaded for the
          request to be valid.
        type: string
        required: false
      addToCollection:
        displayName: Add to Collection
        description: |
          Adds this job to the users collection of jobs.
          
          The user's collection of jobs is what is returned by the `/jobs`
          endpoint.
        type: boolean
        required: false
        default: false


  QueryJobRequestMeta:
    type: object
    additionalProperties: false
    properties:
      summary:
        displayName: Brief Summary
        type: string
        maxLength: 512
      description:
        displayName: Long Description
        type: string

  QueryJobTarget:
    type: object
    additionalProperties: false
    properties:
      organism:
        type: string
      target:
        type: string

  QueryJobListEntry:
    type: object
    additionalProperties: false
    properties:
      queryJobID:
        displayName: Query Job ID
        type: string
        pattern: ^[\dA-Fa-f]{32}$
        minLength: 32
        maxLength: 32
      summary:
        displayName: User Summary
        type: string
        maxLength: 512
      description:
        displayName: User Description
        type: string


  QueryJobDetails: {}

  TargetSite:
    type: string
    enum:
    - AmoebaDB
    - CryptoDB
    - FungiDB
    - GiardiaDB
    - HostDB
    - MicrosporidiaDB
    - PiroplasmaDB
    - PlasmoDB
    - ToxoDB
    - TrichDB
    - TriTrypDB
    - Vectorbase
    - VEuPathDB
