#%RAML 1.0 Library

uses:
  base: ./blast/blast-cli.raml

types:
  QueryJobRequest:
    displayName: Query Job Request
    type: object
    additionalProperties: false
    properties:
      jobConfig:
        displayName: Job Config
        description: Job Configuration.
        type: QueryJobConfig
      blastConfig:
        displayName: Blast Tool Config
        description: |
          Blast Tool Configuration.
          
          Implemented by one of:
          
          - [BlastNConfig](#type:lib.BlastNConfig)
          - [BlastPConfig](#type:lib.BlastPConfig)
          - [BlastXConfig](#type:lib.BlastXConfig)
          - [DeltaBlastConfig](#type:lib.DeltaBlastConfig)
          - [PSIBlastConfig](#type:lib.PSIBlastConfig)
          - [RPSBlastConfig](#type:lib.RPSBlastConfig)
          - [RPSTBlastNConfig](#type:lib.RPSTBlastNConfig)
          - [TBlastNConfig](#type:lib.TBlastNConfig)
          - [TBlastXConfig](#type:lib.TBlastXConfig)
        type: base.BlastQueryConfig
      meta:
        displayName: User Metadata
        type: QueryJobRequestUserMeta
        required: false
        default: null

  QueryJobConfig:
    type: object
    additionalProperties: false
    properties:
      site:
        displayName: Target Site
        type: TargetSite
      targets:
        displayName: Query Targets
        type: array
        items:
          type: QueryJobTarget
        minItems: 1
      query:
        displayName: Blast Query
        description: |
          **For Requests**
          
          Inline query definition.
          
          This field is to be used for non-file-upload blast queries.
          
          If this field is not set, a query file must be uploaded for the
          request to be valid.
          
          **For Responses**
          
          This field will be omitted.
        type: string
        required: false
      addToUserCollection:
        displayName: Add to Collection
        description: |
          Adds this job to the users collection of jobs.
          
          The user's collection of jobs is what is returned by the `/jobs`
          endpoint.
        type: boolean
        required: false
        default: false

  QueryJobRequestUserMeta:
    type: object
    additionalProperties: false
    properties:
      summary:
        displayName: Brief Summary
        description: Brief, user defined summary or tagline for the job.
        type: string
        maxLength: 512
        required: false
      description:
        displayName: Long Description
        description: Longform, user provided description of the job.
        type: string
        required: false

  QueryJobTarget:
    type: object
    additionalProperties: false
    properties:
      organism:
        type: string
      target:
        type: string

  QueryJobListEntry:
    type: object
    additionalProperties: false
    properties:
      queryJobID:
        displayName: Query Job ID
        type: string
        pattern: ^[\dA-Fa-f]{32}$
        minLength: 32
        maxLength: 32
      status:
        displayName: Job Status
        type: JobStatus
      meta:
        displayName: User Metadata
        type: QueryJobRequestUserMeta
        required: false

  QueryJobDetails:
    type: object
    additionalProperties: false
    properties:
      queryJobID:
        displayName: Query Job ID
        type: string
        pattern: ^[\dA-Fa-f]{32}$
        minLength: 32
        maxLength: 32
      status:
        displayName: Job Status
        type: JobStatus
      jobConfig:
        displayName: Job Config
        description: Job Configuration.
        type: QueryJobConfig
      blastConfig:
        displayName: Blast Tool Config
        description: |
          Blast Tool Configuration.
          
          Implemented by one of:
          
          - [BlastNConfig](#type:lib.BlastNConfig)
          - [BlastPConfig](#type:lib.BlastPConfig)
          - [BlastXConfig](#type:lib.BlastXConfig)
          - [DeltaBlastConfig](#type:lib.DeltaBlastConfig)
          - [PSIBlastConfig](#type:lib.PSIBlastConfig)
          - [RPSBlastConfig](#type:lib.RPSBlastConfig)
          - [RPSTBlastNConfig](#type:lib.RPSTBlastNConfig)
          - [TBlastNConfig](#type:lib.TBlastNConfig)
          - [TBlastXConfig](#type:lib.TBlastXConfig)
        type: base.BlastQueryConfig
      meta:
        displayName: User Metadata
        type: QueryJobRequestMeta
        required: false
      subJobs:
        displayName: Sub-Job IDs
        description: List of IDs of sub-jobs that belong to this job.
        type: array
        items:
          type: string
          pattern: ^[\dA-Fa-f]{32}$
          minLength: 32
          maxLength: 32
        minItems: 1
        required: false

  JobBulkStatusResponse:
    displayName: Bulk Job Status Response
    description: |
      Returns a mapping of job-id to status for each of the valid job IDs that
      appeared in the original bulk status request.
    type: object
    properties:
      /^[\dA-Fa-f]{32}$/:
        type: JobStatus

  JobStatus:
    type: string
    enum:
    - queued
    - in-progress
    - complete
    - failed
    - expired

  TargetSite:
    type: string
    enum:
    - AmoebaDB
    - CryptoDB
    - FungiDB
    - GiardiaDB
    - HostDB
    - MicrosporidiaDB
    - PiroplasmaDB
    - PlasmoDB
    - ToxoDB
    - TrichDB
    - TriTrypDB
    - Vectorbase
    - VEuPathDB
