version: "3.5"

services:
  service:
    build:
      context: rest-service

  blast:
    build:
      context: blast/querier

  formatter:
    build:
      context: blast/formatter

  queue-db:
    build:
      context: databases/queue

  queue:
    build:
      context: fireworq
