= MultiBlast
:source-highlighter: highlightjs
:icons: font

image:https://img.shields.io/github/license/veupathdb/service-multi-blast[GitHub]

This repository is a "monorepo" containing various projects relating to and
supporting the VEuPathDB MultiBlast service stack.

For development details and information see the
link:development.adoc[Developer Info] doc.

An index of available API documentation can be found at
https://veupathdb.github.io/service-multi-blast/

== Projects

link:query-service/[BLAST+ Query Service]::
A containerized service whose purpose is the asynchronous execution of BLAST
queries against mounted databases.

link:report-service/[BLAST+ Result Formatting Service]::
A containerized services whose purpose is the asynchronous formatting of ASN.1
BLAST query results into various other formats via the BLAST+ `blast_formatter`
tool.

link:common/blast-types/[BLAST+ CLI API Wrapper Type Library]::
BLAST+ tool CLI API wrapper.
+
Allows easy programmatic construction and validation of CLI calls to BLAST+
tools.

link:common/blast-query-parser/[BLAST+ Query Parsing Tools]::
Multi-sequence BLAST query parsing tool kit.

link:common/mblast-utils/[MultiBlast Common Utilities]::
Various utilities common to the other  services and libraries in this repo.
