openapi: 3.0.3

info:
  title: Blast Worker API
  version: 2.0.0

paths:
  /blast:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./schema/request.json"
      responses:
        200:
          description: "Blast job completed successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    enum:
                      - success
                  message:
                    type: string
                additionalProperties: false
                required:
                  - status
                  - message
        500:
          description: "Blast job failed"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    enum:
                      - permanent-failure
                  message:
                    type: string
                additionalProperties: false
                required:
                  - status
                  - message
  /metrics:
    get:
      responses:
        200:
          description: Success
          content:
            text/plain:
              schema:
                type: string