#%RAML 1.0 Library

types:
  IOBlastConfig:       !include IOBlastConfig.raml
  IOBlastReportField:  !include IOBlastReportField.raml
  IOBlastFormat:       !include IOBlastFormat.raml
  IOBlastReportFormat: !include IOBlastReportFormat.raml
  IOBlastLocation:     !include IOBlastLocation.raml
  IOBlastTool:         !include IOBlastTool.raml
