#%RAML 1.0 Library

types:
  InputBlastConfig:   !include InputBlastConfig.raml
  InputBlastFmtField: !include InputBlastFmtField.raml
  InputBlastFormat:   !include InputBlastFormat.raml
  InputBlastOutFmt:   !include InputBlastOutFmt.raml
  InputBlastLocation: !include InputBlastLocation.raml
  InputBlastTool:     !include InputBlastTool.raml
