#%RAML 1.0 DataType

description: |
  Field Definitions:

  | Field         | Description |
  |---------------|-------------|
  | `qseqid`      | Query Seq-id |
  | `qgi`         | Query GI |
  | `qacc`        | Query accesion |
  | `qaccver`     | Query accesion version |
  | `qlen`        | Query accesion length |
  | `sseqid`      | Subject Seq-id |
  | `sallseqid`   | All subject Seq-id(s), separated by a ';' |
  | `sgi`         | Subject GI |
  | `sallgi`      | All subject GIs |
  | `sacc`        | Subject accession |
  | `saccver`     | Subject accession version |
  | `sallacc`     | All subject accessions |
  | `slen`        | Subject length |
  | `qstart`      | Start of alignment in query |
  | `qend`        | End of alignment in query |
  | `sstart`      | Start of alignment in subject |
  | `send`        | End of alignment in subject |
  | `qseq`        | Aligned part of query sequence |
  | `sseq`        | Aligned part of subject sequence |
  | `evalue`      | Expect value |
  | `bitscore`    | Bit score |
  | `score`       | Raw score |
  | `length`      | Alignment length |
  | `pident`      | Percentage of identical matches |
  | `nident`      | Number of identical matches |
  | `mismatch`    | Number of mismatches |
  | `positive`    | Number of positive-scoring matches |
  | `gapopen`     | Number of gap openings |
  | `gaps`        | Total number of gap |
  | `ppos`        | Percentage of positive-scoring matches |
  | `frames`      | Query and subject frames separated by a '/' |
  | `qframe`      | Query frame |
  | `sframe`      | Subject frame |
  | `btop`        | Blast traceback operations (BTOP) |
  | `staxid`      | unique Subject Taxonomy ID |
  | `ssciname`    | unique Subject Scientific Name |
  | `scomname`    | unique Subject Common Name |
  | `sblastname`  | unique Subject Blast Name |
  | `sskingdom`   | unique Subject Super Kingdom |
  | `staxids`     | unique Subject Taxonomy ID(s), separated by a ';'(in numerical order) |
  | `sscinames`   | unique Subject Scientific Name(s), separated by a ';' |
  | `scomnames`   | unique Subject Common Name(s), separated by a ';' |
  | `sblastnames` | unique Subject Blast Name(s), separated by a ';' (in alphabetical order) |
  | `sskingdoms`  | unique Subject Super Kingdom(s), separated by a ';' (in alphabetical order) |
  | `stitle`      | Subject Title |
  | `salltitles`  | All Subject Title(s), separated by a '&lt;&lt;' |
  | `sstrand`     | Subject Strand |
  | `qcovs`       | Query Coverage Per Subject (for all HSPs) |
  | `qcovhsp`     | Query Coverage Per HSP |
  | `qcovus`      | a measure of Query Coverage that counts a position in a subject sequence for this measure only once. The second time the position is aligned to the query is not counted towards this measure. |
  | `sq`          | Include sequence data (only applicable to blastn fmt 17)
  | `sr`          | Subject as reference seq (only applicable to blastn fmt 17)

  Special fields (only applicable to output type SAM):

  - SQ = Include sequence data
  - SR = Subject as reference seq
type: string
enum:
  - bitscore
  - btop
  - evalue
  - frames
  - gapopen
  - gaps
  - length
  - mismatch
  - nident
  - pident
  - positive
  - ppos
  - qacc
  - qaccver
  - qcovhsp
  - qcovs
  - qcovus
  - qend
  - qframe
  - qgi
  - qlen
  - qseq
  - qseqid
  - qstart
  - sacc
  - saccver
  - sallacc
  - sallgi
  - sallseqid
  - salltitles
  - sblastname
  - sblastnames
  - scomname
  - scomnames
  - score
  - send
  - sframe
  - sgi
  - slen
  - sq
  - sr
  - ssciname
  - sscinames
  - sseq
  - sseqid
  - sskingdom
  - sskingdoms
  - sstart
  - sstrand
  - staxid
  - staxids
  - stitle
