#%RAML 1.0 DataType

uses:
  ext: index.raml

description: |
  Output report format configuration.
type: object
additionalProperties: false
properties:
  format?:
    description: |
      Defaults to `pairwise`
    type: ext.IOBlastFormat
  delim?:
    description: |
      Custom delimiter character.

      Only valid for `tabular`, `tabular-with-comments`, `csv` and `sam`
      formats.

      Default value is dependent on the format type.
    type: string
    minLength: 1
    maxLength: 1
  fields?:
    description: |
      Custom output format fields.

      Allows selecting the specific fields and ordering for a report.

      **Only applicable to the `tabular`, `tabular-with-comments`, and `csv` formats.**

      Defaults to:
      ```json
      [
        "qseqid",
        "sseqid",
        "pident",
        "length",
        "mismatch",
        "gapopen",
        "qstart",
        "qend",
        "sstart",
        "send",
        "evalue",
        "bitscore"
      ]
      ```
    type: array
    items: ext.IOBlastReportField
    uniqueItems: true
    minItems: 1
