#%RAML 1.0 DataType

description: |
  Format Options:

  |  Enum Val                                | Meaning                             |
  |------------------------------------------|-------------------------------------|
  | `pairwise`                               | pairwise                            |
  | `query-anchored-with-identities`         | query-anchored showing identities   |
  | `query-anchored-without-identities`      | query-anchored no identities        |
  | `flat-query-anchored-with-identities`    | flat query-anchored show identities |
  | `flat-query-anchored-without-identities` | flat query-anchored no identities   |
  | `xml`                                    | XML Blast output                    |
  | `tabular`                                | tabular                             |
  | `tabular-with-comments`                  | tabular with comment lines          |
  | `text-asn-1`                             | Text ASN.1                          |
  | `binary-asn-1`                           | Binary ASN.1                        |
  | `csv`                                    | Comma-separated values              |
  | `archive-asn-1`                          | BLAST archive format (ASN.1)        |
  | `seqalign-json`                          | Seqalign (JSON)                     |
  | `multi-file-json`                        | Multiple-file BLAST JSON            |
  | `multi-file-xml2`                        | Multiple-file BLAST XML2            |
  | `single-file-json`                       | Single-file BLAST JSON              |
  | `single-file-xml2`                       | Single-file BLAST XML2              |
  | `sam`                                    | Sequence Alignment/Map (SAM)        |
  | `organism-report`                        | Organism Report                     |

  **Note**: The `sam` output format is only valid for the `blastn` tool.
type: string
enum:
  - pairwise
  - query-anchored-with-identities
  - query-anchored-without-identities
  - flat-query-anchored-with-identities
  - flat-query-anchored-without-identities
  - xml
  - tabular
  - tabular-with-comments
  - text-asn-1
  - binary-asn-1
  - csv
  - archive-asn-1
  - seqalign-json
  - multi-file-json
  - multi-file-xml2
  - single-file-json
  - single-file-xml2
  - sam
  - organism-report
