#%RAML 1.0 DataType
#
#uses:
#  blastp: ../blastp/index.raml
#  blast:  ../blast/index.raml
#  ext:    index.raml
#  com:    ../blast-common/index.raml
#
#type: blast.IOBlastConfig
#discriminatorValue: rpsblast
#additionalProperties: false
#properties:
#
#  windowSize?:
#    description: |
#      Multiple hits window size, use 0 to specify 1-hit algorithm.
#    type: integer
#    default: 40
#    format: int16
#    minimum: 0
#
#  xdropUngap?:
#    description: |
#      Heuristic value (in bits) for ungapped extensions
#    type: number
#    format: double
#    default: 15.0
#
#  xdropGap?:
#    description: |
#      Heuristic value (in bits) for preliminary gapped extensions.
#    type: number
#    format: double
#    default: 25.0
#
#  xdropGapFinal?:
#    description: |
#      Heuristic value (in bits) for final gapped alignment.
#    type: number
#    format: double
#    default: 40.0
#
#  seg?:
#    description: |
#      Filter query sequence with SEG.
#    type: com.IOBlastSegMask
#    default:
#      window: 12
#      locut: 2.2
#      hicut: 2.5
#
#  softMasking?:
#    description: |
#      Apply filtering locations as soft masks (i.e., only for finding initial
#      matches).
#    type: boolean
#    default: false
