package org.veupathdb.service.multiblast.model.io;

public final class JsonKeys
{
  public static final String
    BEST_HIT_OVERHANG    = "bestHitOverhang",
    BEST_HIT_SCORE_EDGE  = "bestHitScoreEdge",
    CULLING_LIMIT        = "cullingLimit",
    DB                   = "db",
    DB_HARD_MASK         = "dbHardMask",
    DB_SIZE              = "dbSize",
    DB_SOFT_MASK         = "dbSoftMask",
    DELIMITER            = "delim",
    DUST                 = "dust",
    E_VALUE              = "eValue",
    FIELDS               = "fields",
    FILTERING_DB         = "filteringDb",
    FORMAT               = "format",
    GAP_EXTEND           = "gapExtend",
    GAP_OPEN             = "gapOpen",
    GI_LIST              = "giList",
    INDEX_NAME           = "indexName",
    LCASE_MASKING        = "lcaseMasking",
    MAX_HSPS             = "maxHSPs",
    MAX_TARGET_SEQS      = "maxTargetSeqs",
    MIN_RAW_GAPPED_SCORE = "minRawGappedScore",
    NEGATIVE_GI_LIST     = "negativeGiList",
    NEGATIVE_SEQ_ID_LIST = "negativeSeqIdList",
    NEGATIVE_TAX_ID_LIST = "negativeTaxIdList",
    NEGATIVE_TAX_IDS     = "negativeTaxIds",
    NO_GREEDY            = "noGreedy",
    NUM_ALIGNMENTS       = "numAlignments",
    NUM_DESCRIPTIONS     = "numDescriptions",
    OUT_FMT              = "outFmt",
    PARSE_DEF_LINES      = "parseDefLines",
    PENALTY              = "penalty",
    PERC_IDENTITY        = "percIdentity",
    QUERY                = "query",
    QUERY_LOC            = "queryloc",
    REMOTE               = "remote",
    REWARD               = "reward",
    SEARCH_SPACE         = "searchSpace",
    SEQ_ID_LIST          = "seqIdList",
    SOFT_MASKING         = "softMasking",
    SORT_HITS            = "sortHits",
    SORT_HSPS            = "sortHSPs",
    STRAND               = "strand",
    SUBJECT              = "subject",
    SUBJECT_LOC          = "subjectLoc",
    TASK                 = "task",
    TAX_ID_LIST          = "taxIdList",
    TAX_IDS              = "taxIds",
    TEMPLATE_LENGTH      = "templateLength",
    TEMPLATE_TYPE        = "templateType",
    TOOL                 = "tool",
    UNGAPPED             = "ungapped",
    USE_INDEX            = "useIndex",
    WINDOW_MASKER_DB     = "windowMaskerDb",
    WINDOW_MASKER_TAXID  = "windowMaskerTaxid",
    WINDOW_SIZE          = "windowSize",
    WORD_SIZE            = "wordSize",
    XDROP_GAP            = "xdropGap",
    XDROP_GAP_FINAL      = "xdropGapFinal",
    XDROP_UNGAP          = "xdropUngap";

  private JsonKeys() {
  }
}
