version: "3.5"

services:
  # #
  # Public facing REST API
  # #
  service:
    build:
      dockerfile: Dockerfile
      context: ../rest-service
    # These values can be provided using the .env template file
    ports:
      - 8080:80
    environment:
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}
      SERVER_PORT: ${SERVER_PORT:-80}
      LDAP_SERVER: ${LDAP_SERVER}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN}

      # Account Database
      ACCT_DB_TNS_NAME:
      ACCT_DB_USER:
      ACCT_DB_PASS:

      # User Database
      USER_DB_TNS_NAME:
      USER_DB_USER:
      USER_DB_PASS:
      MULTIBLAST_SCHEMA:

      # Queue Connection
      QUEUE_HOST:

      # Misc Config
      JOB_MOUNT_PATH: /out
      DB_MOUNT_PATH: /db
      DB_BUILD: ${DB_BUILD:-52}
      BLAST_HOST: ${BLAST_HOST:-blast}
      BLAST_QUEUE_NAME: ${BLAST_QUEUE_NAME:-blast}
      BLAST_JOB_CATEGORY: ${BLAST_JOB_CATEGORY:-blast}

      FORMATTER_HOST: ${FORMATTER_HOST:-formatter}
      FORMAT_QUEUE_NAME: ${FORMAT_QUEUE_NAME:-format}
      FORMAT_JOB_CATEGORY: ${FORMAT_JOB_CATEGORY:-format}

      VALIDATOR_HOST: ${VALIDATOR_HOST:-validator}

      # Job Config
      #
      # These options configure the validation/management of jobs.
      JOB_TIMEOUT: ${JOB_TIMEOUT:-30} #days
      MAX_QUERIES_PER_REQUEST: ${MAX_QUERIES_PER_REQUEST:-100}
      MAX_RESULTS_PER_QUERY: ${MAX_RESULTS_PER_QUERY:-10000}
      MAX_INPUT_QUERY_SIZE: ${MAX_INPUT_QUERY_SIZE:-3145728} # 3MiB
      MAX_NA_SEQ_SIZE: ${MAX_NA_SEQ_SIZE:-1048576} # 1MiB
      MAX_AA_SEQ_SIZE: ${MAX_AA_SEQ_SIZE:-102400} # 100KiB

    volumes:
      # Replace `source` with the path you would like the job workspace to
      # reside in your development environment.
      - type: bind # volume
        source: /home/ellie/blastout # job-data
        target: /out
        # Replace `source` with the path to the blast db files available in your
        # work environment.
      - type: bind # volume
        source: /home/ellie/blastdb # blast-data
        target: /db
    depends_on:
      - queue
      - validator
    network_mode: host

  # #
  # Blast Query Runner (Job Queue Managed)
  # #
  blast:
    build:
      dockerfile: Dockerfile
      context: ../blast/querier
    environment:
      DB_MOUNT_PATH: /db
      JOB_MOUNT_PATH: /out
    ports:
      - 8081:80
    volumes:
      # Replace `source` with the path you would like the job workspace to
      # reside in your development environment.
      - type: bind # volume
        source: /home/ellie/blastout # job-data
        target: /out
        # Replace `source` with the path to the blast db files available in your
        # work environment.
      - type: bind # volume
        source: /home/ellie/blastdb # blast-data
        target: /db

  # #
  # Blast Result Formatter
  # #
  formatter:
    build:
      dockerfile: Dockerfile
      context: ../blast/formatter
    environment:
      DB_MOUNT_PATH: /db
      JOB_MOUNT_PATH: /out
    ports:
      - 8082:80
    volumes:
      # Replace `source` with the path you would like the job workspace to
      # reside in your development environment.
      - type: bind # volume
        source: /home/ellie/blastout # job-data
        target: /out
        # Replace `source` with the path to the blast db files available in your
        # work environment.
      - type: bind # volume
        source: /home/ellie/blastdb # blast-data
        target: /db

  # #
  # MySQL backing database queue persistence
  # #
  queue-db:
    build:
      dockerfile: Dockerfile
      context: ../databases/queue
    environment:
      # Root user password (IT'S A SECRET TO EVERYBODY)
      MYSQL_ROOT_PASSWORD:
      # Service user username
      QUEUE_DB_USER: queue
      # Service user password
      QUEUE_DB_PASS:

  # #
  # Job Queue
  # #
  queue:
    build:
      context: ../fireworq
    environment:
      # REQUIRED!
      # Specifies a data source name for the job queue and the repository
      # database in a form user:password@tcp(mysql_host:mysql_port)/database?options
      #
      # The password value here must match the `MYSQL_PASSWORD` value for
      # the queue-db container.
      FIREWORQ_MYSQL_DSN: # queue:<some password here>@tcp(queue-db:3306)/queue

      # Configures the number of simultaneous blast jobs that can be run
      FIREWORQ_QUEUE_DEFAULT_MAX_WORKERS: 2

      FIREWORQ_BIND: 0.0.0.0:80
      FIREWORQ_DRIVER: mysql
      JOB_CATEGORY: blast
    ports:
      - 8083:80
    depends_on:
      - queue-db
      - blast
      - formatter

  ##
  # Blast config validator
  ##
  validator:
    build:
      context: ../blast/validator
    ports:
      - 8084:80


volumes:
  blast-data:

  job-data:
