version: "3.5"

services:
  service-db:
    image: postgres/13-alpine
    volumes:
      - type: bind
        volume:
          nocopy: true
        source: ../databases/service
        target: /docker-entrypoint-initdb.d
    environment:
      # Postgres root user password
      POSTGRES_PASSWORD:
      # Service user username
      SVC_DB_USER:
      # Service user password
      SVC_DB_PASS:
    networks:
      - serviceInternal

  service:
    build:
      dockerfile: ../rest-service/Dockerfile
      context: ../rest-service
    environment:
      SVC_DB_USER:
      SVC_DB_PASS:

    volumes:
      - type: volume
        source: job-data
        target: /jobs
    networks:
      - serviceInternal
      - serviceShared
    depends_on:
      - queue
      - service-db

  blast:
    build:
      dockerfile: ../blast/Dockerfile
      context: ../blast
    volumes:
      - type: volume
        source: job-data
        target: /out
      - type: volume
        source: blast-data
        target: /db
    networks:
      - blastInternal

  queue-db:
    image: mysql:8
    environment:
      # Root user password (IT'S A SECRET TO EVERYBODY)
      MYSQL_ROOT_PASSWORD: 1234
      # Service user username
      QUEUE_DB_USER: queue
      # Service user password
      QUEUE_DB_PASS: 1234
    networks:
      - queueInternal

  queue:
    image: fireworq/fireworq:1.4
    environment:
      # REQUIRED!
      # Specifies a data source name for the job queue and the repository
      # database in a form user:password@tcp(mysql_host:mysql_port)/database?options
      #
      # The password value here must match the `MYSQL_PASSWORD` value for
      # the queue-db container.
      FIREWORQ_MYSQL_DSN: queue:1234@tcp(queue-db:3306)/queue

      # Configures the number of simultaneous blast jobs that can be run
      FIREWORQ_QUEUE_DEFAULT_MAX_WORKERS: 2

      FIREWORQ_BIND: 0.0.0.0:80
      FIREWORQ_DRIVER: mysql
      FIREWORQ_QUEUE_DEFAULT: blast

    networks:
      - queueInternal
      - blastInternal
      - serviceShared
    depends_on:
      - queue-db
      - blast

networks:
  blastInternal:
  queueInternal:
  serviceInternal:
  serviceShared:

volumes:
  blast-data:
  job-data:
