```mermaid
sequenceDiagram

participant C as Client
participant P as Public Service
participant V as Config Validator
participant Q as Job Queue
participant B as Blast Service

C ->> P: Blast Config
activate P
P ->> V: Blast Config
activate V
alt Config Is Invalid
V -->> P: Validation error
deactivate V
P -->> C: Validation error
else Config Is Valid
P ->> Q: Blast Config
activate Q
Q -->> P: Queue ID
deactivate Q
P -->> C: Blast Job ID
deactivate P
end

Q ->> B: Blast Config
activate B
B -->> Q: Status
deactivate B

C ->> P: Blast Job ID
activate P
P ->> Q: Queue ID
activate Q
Q -->> P: Status
deactivate Q
P -->> C: Status
deactivate P
```