```mermaid
sequenceDiagram

participant C as Client
participant P as Public Service
participant V as Config Validator
participant Q as Job Queue
participant B as Blast Formatter

C ->> P: Formatter Config
activate P
P ->> V: Formatter Config
activate V
alt Config Is Invalid
V -->> P: Validation error
deactivate V
P -->> C: Validation error
else Config Is Valid
P ->> Q: Formatter Config
activate Q
Q -->> P: Queue ID
deactivate Q
P -->> C: Format Job ID
deactivate P
end

Q ->> B: Formatter Config
activate B
B -->> Q: Status
deactivate B

C ->> P: Format Job ID
activate P
P ->> Q: Queue ID
activate Q
Q -->> P: Status
deactivate Q
P -->> C: Status
deactivate P

C ->> P: Get Report File
activate P
P -->> C: File Contents
deactivate P
```