#%RAML 1.0 DataType

description: |
   | Task           | Use Case                                                 |
   |----------------|----------------------------------------------------------|
   | `blastp`       |  for standard protein-protein comparisons                |
   | `blastp-short` | optimized for query sequences shorter than 30 residues   |
   | `blastp-fast`  | a faster version that uses a larger word-size per https://www.ncbi.nlm.nih.gov/pubmed/17921491 |
type: string
enum:
  - blastp
  - blastp-short
  - blastp-fast
