#%RAML 1.0 Library

types:
  IOBlastCompBasedStats: !include IOBlastCompBasedStats.raml
  IOBlastScoringMatrix:  !include IOBlastScoringMatrix.raml
  IOBlastSegMask:        !include IOBlastSegMask.raml
  IOBlastStrand:         !include IOBlastStrand.raml
  IOHitSorting:          !include IOHitSorting.raml
  IOHSPSorting:          !include IOHSPSorting.raml
