#%RAML 1.0 Library

types:
  InputBlastCompBasedStats: !include InputBlastCompBasedStats.raml
  InputBlastScoringMatrix:  !include InputBlastScoringMatrix.raml
  InputBlastSegMask:        !include InputBlastSegMask.raml
  InputBlastStrand:         !include InputBlastStrand.raml
  InputHitSorting:          !include InputHitSorting.raml
  InputHSPSorting:          !include InputHSPSorting.raml
