#%RAML 1.0 DataType

description: |
  | Value                                     | Description                    |
  |-------------------------------------------|--------------------------------|
  | none                                      | no composition-based statistics |
  | comp-based-stats                          | Composition-based statistics as in NAR 29:2994-3005, 2001 |
  | conditional-comp-based-score-adjustment   | Composition-based score adjustment as in Bioinformatics 21:902-911, 2005, conditioned on sequence properties |
  | unconditional-comp-based-score-adjustment | Composition-based score adjustment as in Bioinformatics 21:902-911, 2005, unconditionally |
type: string
enum:
  - none
  - comp-based-stats
  - conditional-comp-based-score-adjustment
  - unconditional-comp-based-score-adjustment
