openapi: 3.0.3
info:
  title: Blast+ Report Translator
  description: |
    Server interface over the `blast_formatter` tool used to translate a blast+
    report into various desired output formats.
  version: 1.0.0
paths:
  /translate/{jobHash}:
    parameters:
      - $ref: '#/components/parameters/jobHash'
    get:
      summary: List Cached Reports
      description: |
        Returns a list of already cached report formats.  These are translations
        that have already been run for the specified job.
        <br><br>
        The returned set of cached report formats will be returned as a map of
        report format view option keys mapped to a list of cached files for that
        translation.
      responses:
        200:
          description: "Success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listBody'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /translate/{jobHash}/6:
    parameters:
      - $ref: '#/components/parameters/jobHash'
    put:
      requestBody:
        $ref: '#/components/requestBodies/form6_7_10RB'
      summary: Translate Report Type 6
      responses:
        200:
          $ref: '#/components/responses/Job200'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /translate/{jobHash}/7:
    parameters:
      - $ref: '#/components/parameters/jobHash'
    put:
      requestBody:
        $ref: '#/components/requestBodies/form6_7_10RB'
      summary: Translate Report Type 7
      responses:
        200:
          $ref: '#/components/responses/Job200'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /translate/{jobHash}/10:
    parameters:
      - $ref: '#/components/parameters/jobHash'
    put:
      requestBody:
        $ref: '#/components/requestBodies/form6_7_10RB'
      summary: Translate Report Type 10
      responses:
        200:
          $ref: '#/components/responses/Job200'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'

  /translate/{jobHash}/17:
    parameters:
      - $ref: '#/components/parameters/jobHash'
    put:
      requestBody:
        $ref: '#/components/requestBodies/form17RB'
      summary: Translate Report Type 17
      responses:
        200:
          $ref: '#/components/responses/Job200'
        400:
          $ref: '#/components/responses/400'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'


  /translate/{jobHash}/{reportType}:
    parameters:
      - $ref: '#/components/parameters/jobHash'
      - $ref: '#/components/parameters/reportType'
    put:
      summary: Translate Non-Parameterized Report
      responses:
        200:
          $ref: '#/components/responses/Job200'
        404:
          $ref: '#/components/responses/404'
        500:
          $ref: '#/components/responses/500'


components:
  responses:
    Job200:
      description: Success
      content:
        application/zip:
          schema:
            type: string
            format: binary
    400:
      description: Invalid client input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorBody'
    404:
      description: Unknown job hash
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorBody'
    500:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorBody'


  requestBodies:
    form17RB:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/form17Body'
    form6_7_10RB:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/form6_7_10Body'

  parameters:
    jobHash:
      name: jobHash
      in: path
      required: true
      description: |
        Base16 encoded job identifier hash.
      schema:
        type: string
        pattern: '^[0-9a-fA-F]{64}$'
        minLength: 64
        maxLength: 64
    reportType:
      name: reportType
      in: path
      required: true
      description: |
        Output report format option.

        ```
         0 = Pairwise,
         1 = Query-anchored showing identities,
         2 = Query-anchored no identities,
         3 = Flat query-anchored showing identities,
         4 = Flat query-anchored no identities,
         5 = BLAST XML,
         8 = Seqalign (Text ASN.1),
         9 = Seqalign (Binary ASN.1),
        11 = BLAST archive (ASN.1),
        12 = Seqalign (JSON),
        13 = Multiple-file BLAST JSON,
        14 = Multiple-file BLAST XML2,
        15 = Single-file BLAST JSON,
        16 = Single-file BLAST XML2,
        18 = Organism Report
        ```
      schema:
        $ref: '#/components/schemas/reportType'
  schemas:
    errorBody:
      type: object
      properties:
        type:
          type: string
        message:
          type: string
        requestID:
          type: string
      required:
        - type
        - message
        - requestID

    listBody:
      type: object
      properties:
        0: { $ref: '#/components/schemas/fileList' }
        1: { $ref: '#/components/schemas/fileList' }
        2: { $ref: '#/components/schemas/fileList' }
        3: { $ref: '#/components/schemas/fileList' }
        4: { $ref: '#/components/schemas/fileList' }
        5: { $ref: '#/components/schemas/fileList' }
        6: { $ref: '#/components/schemas/fileList' }
        7: { $ref: '#/components/schemas/fileList' }
        8: { $ref: '#/components/schemas/fileList' }
        9: { $ref: '#/components/schemas/fileList' }
        10: { $ref: '#/components/schemas/fileList' }
        11: { $ref: '#/components/schemas/fileList' }
        12: { $ref: '#/components/schemas/fileList' }
        13: { $ref: '#/components/schemas/fileList' }
        14: { $ref: '#/components/schemas/fileList' }
        15: { $ref: '#/components/schemas/fileList' }
        16: { $ref: '#/components/schemas/fileList' }
        17: { $ref: '#/components/schemas/fileList' }
        18: { $ref: '#/components/schemas/fileList' }

    reportType:
      type: integer
      format: byte
      minimum: 0
      maximum: 18

    fileList:
      type: array
      uniqueItems: true
      items:
        type: string
        format: uri
    form17Body:
      type: object
      properties:
        fields:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/form17Fields'
    form17Fields:
      type: string
      enum:
        - SQ
        - SR
    form6_7_10Body:
      type: object
      properties:
        delim:
          description: Delimeter character.
          type: string
          minLength: 1
          maxLength: 1
        fields:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/form6_7_10Fields'
    form6_7_10Fields:
      type: string
      enum: [ qseqid, qgi, qacc, qaccver, qlen, sseqid, sallseqid, sgi, sallgi,
              sacc, saccver, sallacc, slen, qstart, qend, sstart, send, qseq,
              sseq, evalue, bitscore, score, length, pident, nident, mismatch,
              positive, gapopen, gaps, ppos, frames, qframe, sframe, btop,
              staxid, ssciname, scomname, sblastname, sskingdom, staxids,
              sscinames, scomnames, sblastnames, sskingdoms, stitle, salltitles,
              sstrand, qcovs, qcovhsp, qcovus ]
