CREATE TABLE multi_blast.tools_to_options
(
  tool_id   SMALLINT REFERENCES multi_blast.tools (tool_id)
, option_id SMALLINT REFERENCES multi_blast.tool_options (option_id)
);

--------------------------------------------------------------------------------
--
-- BLASTN Options
--
--------------------------------------------------------------------------------
INSERT INTO
  multi_blast.tools_to_options (tool_id, option_id)
VALUES
  (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_overhang'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_score_edge'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'culling_limit'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db_hard_mask'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db_soft_mask'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'dbsize'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'dust'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'entrez_query'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'evalue'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'export_search_strategy'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'filtering_db'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gapextend'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gapopen'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gilist'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'html'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'import_search_strategy'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'index_name'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'lcase_masking'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'line_length'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_hsps'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_target_seqs'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'min_raw_gapped_score'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_gilist'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_seqidlist'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_taxidlist'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_taxids'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'no_greedy'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_alignments'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_descriptions'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_threads'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'off_diagonal_range'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'out'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'outfmt'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'parse_deflines'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'penalty'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'perc_identity'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'qcov_hsp_perc'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query_loc'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'remote'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'reward'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'searchsp'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'seqidlist'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'show_gis'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'soft_masking'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthits'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthsps'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'strand'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject_besthit'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject_loc'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sum_stats'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'task'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'taxidlist'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'taxids'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'template_length'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'template_type'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'ungapped'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'use_index'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'version'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'window_masker_db'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'window_masker_taxid'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'window_size'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'word_size'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap_final'))
, (1, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_ungap'))
;

--------------------------------------------------------------------------------
--
-- BLASTP Options
--
--------------------------------------------------------------------------------
INSERT INTO
  multi_blast.tools_to_options (tool_id, option_id)
VALUES
  (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_overhang'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_score_edge'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'comp_based_stats'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'culling_limit'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db_hard_mask'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db_soft_mask'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'dbsize'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'entrez_query'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'evalue'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'export_search_strategy'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gapextend'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gapopen'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gilist'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'html'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'import_search_strategy'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'ipglist'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'lcase_masking'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'line_length'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'matrix'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_hsps'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_target_seqs'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_gilist'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_ipglist'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_seqidlist'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_taxidlist'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_taxids'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_alignments'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_descriptions'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_threads'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'out'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'outfmt'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'parse_deflines'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'qcov_hsp_perc'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query_loc'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'remote'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'searchsp'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'seg'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'seqidlist'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'show_gis'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'soft_masking'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthits'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthsps'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject_besthit'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject_loc'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'task'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'taxidlist'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'taxids'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'threshold'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'ungapped'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'use_sw_tback'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'version'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'window_size'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'word_size'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap_final'))
, (2, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_ungap'))
;

--------------------------------------------------------------------------------
--
-- BLASTX Options
--
--------------------------------------------------------------------------------
INSERT INTO
  multi_blast.tools_to_options (tool_id, option_id)
VALUES
  (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_overhang'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_score_edge'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'comp_based_stats'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'culling_limit'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db_hard_mask'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db_soft_mask'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'dbsize'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'entrez_query'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'evalue'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'export_search_strategy'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gapextend'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gapopen'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gilist'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'html'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'import_search_strategy'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'ipglist'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'lcase_masking'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'line_length'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'matrix'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_hsps'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_intron_length'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_target_seqs'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_gilist'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_ipglist'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_seqidlist'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_taxidlist'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_taxids'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_alignments'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_descriptions'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_threads'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'out'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'outfmt'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'parse_deflines'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'qcov_hsp_perc'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query_gencode'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query_loc'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'remote'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'searchsp'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'seg'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'seqidlist'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'show_gis'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'soft_masking'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthits'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthsps'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'strand'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject_besthit'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject_loc'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sum_stats'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'task'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'taxidlist'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'taxids'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'threshold'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'ungapped'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'use_sw_tback'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'version'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'window_size'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'word_size'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap_final'))
, (3, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_ungap'))
;

--------------------------------------------------------------------------------
--
-- TBLASTN Options
--
--------------------------------------------------------------------------------
INSERT INTO
  multi_blast.tools_to_options (tool_id, option_id)
VALUES
  (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_overhang'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_score_edge'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'comp_based_stats'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'culling_limit'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db_gencode'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db_hard_mask'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db_soft_mask'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'dbsize'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'entrez_query'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'evalue'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'export_search_strategy'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gapextend'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gapopen'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gilist'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'html'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'import_search_strategy'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'in_pssm'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'lcase_masking'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'line_length'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'matrix'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_hsps'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_intron_length'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_target_seqs'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_gilist'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_seqidlist'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_taxidlist'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_taxids'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_alignments'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_descriptions'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_threads'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'out'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'outfmt'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'parse_deflines'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'qcov_hsp_perc'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query_loc'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'remote'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'searchsp'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'seg'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'seqidlist'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'show_gis'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'soft_masking'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthits'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthsps'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject_besthit'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject_loc'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sum_stats'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'task'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'taxidlist'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'taxids'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'threshold'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'ungapped'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'use_sw_tback'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'version'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'window_size'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'word_size'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap_final'))
, (4, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_ungap'))
;

--------------------------------------------------------------------------------
--
-- TBLASTX Options
--
--------------------------------------------------------------------------------
INSERT INTO
  multi_blast.tools_to_options (tool_id, option_id)
VALUES
  (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_overhang'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_score_edge'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'culling_limit'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db_gencode'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db_hard_mask'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db_soft_mask'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'dbsize'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'entrez_query'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'evalue'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'export_search_strategy'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gilist'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'html'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'import_search_strategy'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'lcase_masking'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'line_length'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'matrix'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_hsps'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_intron_length'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_target_seqs'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_gilist'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_seqidlist'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_taxidlist'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_taxids'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_alignments'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_descriptions'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_threads'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'out'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'outfmt'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'parse_deflines'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'qcov_hsp_perc'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query_gencode'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query_loc'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'remote'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'searchsp'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'seg'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'seqidlist'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'show_gis'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'soft_masking'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthits'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthsps'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'strand'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject_besthit'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject_loc'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sum_stats'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'taxidlist'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'taxids'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'threshold'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'version'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'window_size'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'word_size'))
, (5, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_ungap'))
;

--------------------------------------------------------------------------------
--
-- RPSBLAST Options
--
--------------------------------------------------------------------------------
INSERT INTO
  multi_blast.tools_to_options (tool_id, option_id)
VALUES
  (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_overhang'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_score_edge'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'comp_based_stats'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'culling_limit'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'dbsize'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'entrez_query'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'evalue'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'export_search_strategy'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'html'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'import_search_strategy'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'lcase_masking'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'line_length'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_hsps'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_target_seqs'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_alignments'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_descriptions'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_threads'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'out'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'outfmt'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'parse_deflines'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'qcov_hsp_perc'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query_loc'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'remote'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'searchsp'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'seg'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'show_gis'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'soft_masking'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthits'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthsps'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject_besthit'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sum_stats'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'use_sw_tback'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'version'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'window_size'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap_final'))
, (6, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_ungap'))
;

--------------------------------------------------------------------------------
--
-- RPSTBLASTN Options
--
--------------------------------------------------------------------------------
INSERT INTO
  multi_blast.tools_to_options (tool_id, option_id)
VALUES
  (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'comp_based_stats'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'dbsize'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'entrez_query'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'evalue'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'export_search_strategy'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'html'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'import_search_strategy'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'lcase_masking'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'line_length'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_hsps'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_target_seqs'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_alignments'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_descriptions'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_threads'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'out'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'outfmt'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'parse_deflines'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'qcov_hsp_perc'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query_gencode'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query_loc'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'remote'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'searchsp'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'seg'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'show_gis'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'soft_masking'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthits'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthsps'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'strand'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sum_stats'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'ungapped'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'use_sw_tback'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'version'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'window_size'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap_final'))
, (7, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_ungap'))
;

--------------------------------------------------------------------------------
--
-- PSIBLAST Options
--
--------------------------------------------------------------------------------
INSERT INTO
  multi_blast.tools_to_options (tool_id, option_id)
VALUES
  (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = ' -save_ascii_pssm'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_overhang'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'best_hit_score_edge'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'comp_based_stats'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'culling_limit'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'db'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'dbsize'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'entrez_query'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'evalue'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'export_search_strategy'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gap_trigger'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gapextend'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gapopen'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'gilist'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'html'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'ignore_msa_master'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'import_search_strategy'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'in_msa'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'in_pssm'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'inclusion_ethresh'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'ipglist'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'lcase_masking'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'line_length'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'matrix'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_hsps'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'max_target_seqs'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'msa_master_idx'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_gilist'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_ipglist'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_seqidlist'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_taxidlist'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'negative_taxids'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_alignments'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_descriptions'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_iterations'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'num_threads'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'out'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'out_ascii_pssm'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'out_pssm'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'outfmt'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'parse_deflines'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'phi_pattern'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'pseudocount'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'qcov_hsp_perc'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'query_loc'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'remote'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'save_each_pssm'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'save_pssm_after_last_round'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'searchsp'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'seg'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'seqidlist'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'show_gis'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'soft_masking'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthits'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sorthsps'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject_besthit'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'subject_loc'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'sum_stats'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'taxidlist'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'taxids'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'threshold'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'use_sw_tback'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'version'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'window_size'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'word_size'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_gap_final'))
, (8, (SELECT option_id FROM multi_blast.tool_options WHERE name = 'xdrop_ungap'))
;
