#%RAML 1.0 Library

# Blast CLI Flags and Arguments Common to all Blast+ Query Tools

types:
  # Base Query Tool Configuration Object
  #
  # The properties defined on this object are flags and arguments that are
  # common to all Blast+ CLI tools used by the mblast query process.
  #
  # The target tools are:
  #
  # - blastn
  # - blastp
  # - blastx
  # - deltablast
  # - psiblast
  # - rpsblast
  # - rpstblastn
  # - tblastn
  # - tblastx
  BlastQueryConfig:
    type: object
    additionalProperties: false
    discriminator: tool
    properties:
      tool:
        displayName: Blast Tool
        description: Target Blast+ query tool to execute.
        type: BlastQueryTool
        required: true
      queryLocation:
        displayName: Query Location
        description: Location on the query sequence in 1-based offsets.
        type: BlastLocation
        required: false
        default: null
      eValue:
        displayName: Expectation Value
        description: Expectation value (E) threshold for saving hits.
        type: string
        pattern: ^\d+(?:\.\d+)?(?:[eE]-?\d+)?$
        required: false
        default: '10'
      softMasking:
        displayName: Soft Masking
        description: Apply filtering locations as soft masks.
        type: boolean
        required: false
        default: false
      lowercaseMasking:
        displayName: Lowercase Masking
        description: Use lower case filtering in query and subject sequence(s)?
        type: boolean
        required: false
        default: false
      queryCoverageHSPPercent:
        displayName: Query Coverage HSP Percent
        description: Percent query coverage per High Scoring Pair.
        type: number
        format: double
        minimum: 0.0
        maximum: 100.0
        required: false
        default: null
      maxHSPs:
        displayName: Max HSPs
        description: |
          Set maximum number of High Scoring Pairs per subject sequence to save
          for each query.
        type: integer
        format: int
        minimum: 1
        required: false
        default: null
      maxTargetSequences:
        displayName: Max Target Sequences
        description: Maximum number of aligned sequences to keep.
        type: integer
        minimum: 5
        required: false
        default: 500
      dbSize:
        displayName: DB Size
        description: Effective length of the database.
        type: integer
        format: int8
        minimum: -128
        maximum: 127
        required: false
        default: null
      searchSpace:
        displayName: Search Space
        description: Effective length of the search space.
        type: integer
        format: int8
        minimum: 0
        maximum: 127
        required: false
        default: null
      xDropoffUngapped:
        displayName: Ungapped Extension X-Dropoff
        description: X-dropoff value (in bits) for ungapped extensions
        type: number
        format: double
        required: false
        default: null
      windowSize:
        displayName: Window Size
        description: |
          Multiple hits window size.
          
          0 to specify 1-hit algorithm.
        type: integer
        format: int
        minimum: 0
        required: false
        default: null
      parseDefLines:
        displayName: Parse Query Definition Lines
        description: Should the query and subject defline(s) be parsed?
        type: boolean
        required: false
        default: false

  BlastSeg:
    type: object
    additionalProperties: false
    properties:
      window:
        displayName: Window
        description: SEG window.
        type: integer
        format: int
        required: false
        default: 12
      locut:
        displayName: Locut
        description: SEG locut.
        type: number
        format: double
        required: false
        default: 2.2
      hicut:
        displayName: Hicut
        description: SEG hicut.
        type: number
        format: double
        required: false
        default: 2.5


  BlastQueryTool:
    type: string
    enum:
    - blastn
    - blastp
    - blastx
    - deltablast
    - psiblast
    - rpsblast
    - rpstblastn
    - tblastn
    - tblastx

  BlastGenCode:
    description: |
      Translation Gen Code
      
      Valid values are:
      - 1, 2, 3, 4, 5, 6
      - 9, 10, 11, 12, 13, 14, 15, 16
      - 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31
      - 33
      
      This type _should_ be an enum, however the code generated from the RAML
      when it _is_ an enum is broken.
    type: integer
    format: int8
    minimum: 1
    maximum: 33

  BlastLocation:
    type: object
    additionalProperties: false
    properties:
      start:
        type: integer
        format: long
        minimum: 0
      stop:
        type: integer
        format: long
        minimum: 0

  BlastStrand:
    type: string
    enum:
    - both
    - minus
    - plus