#%RAML 1.0 Library

uses:
  base: ./blast-cli.raml

types:
  DeltaBlastConfig:
    type: base.BlastQueryConfig
    discriminatorValue: deltablast
    additionalProperties: false
    properties:
      wordSize:
        displayName: Word Size
        description: |
          Word size for wordfinder algorithm (length of best perfect match).
        type: integer
        format: int
        minimum: 2
        required: false
        default: null
      gapOpen:
        displayName: Gap Open
        description: Cost to open a gap.
        type: integer
        format: int
        required: false
        default: null
      gapExtend:
        displayName: Gap Extend
        description: Cost to extend a gap.
        type: integer
        format: int
        required: false
        default: null
      matrix:
        displayName: Scoring Matrix
        description: Scoring matrix name (normally BLOSUM62)
        type: DeltaBlastMatrix
        required: false
        default: null
      threshold:
        displayName: Minimum Word Score Threshold
        description: |
          Minimum word score such that the word is added to the BLAST lookup
          table.
        type: number
        format: double
        minimum: 0.0
        required: false
        default: null
      compBasedStats:
        displayName: Composition Based Statistics
        description: |
          Use composition-based statistics:
          
          - No composition-based statistics
          - Composition-based statistics as in NAR 29:2994-3005, 2001
        type: DeltaBlastCompBasedStats
        required: false
        default: comp-based-stats
      seg:
        displayName: SEG
        description: Filter query sequence with SEG.
        type: base.BlastSeg
        required: false
        default: null
      cullingLimit:
        displayName: Culling Limit
        description: |
          If the query range of a hit is enveloped by that of at least this many
          higher-scoring hits, delete the hit
          
          Incompatible with: 
          - `bestHitOverhang`
          - `bestHitScoreEdge`
        type: integer
        format: int
        minimum: 0
        required: false
        default: null
      bestHitOverhang:
        displayName: Best Hit Overhang
        description: |
          Best Hit algorithm overhang value (recommended value: 0.1)
          
          Incompatible with:
          - `cullingLimit`
        type: number
        format: double
        minimum: 0.000000000000001
        maximum: 0.499999999999999
        required: false
        default: null
      bestHitScoreEdge:
        displayName: Best Hit Score Edge
        description: |
          Best Hit algorithm score edge value (recommended value: 0.1)
          
          Incompatible with:
          - `cullingLimit`
        type: number
        format: double
        minimum: 0.000000000000001
        maximum: 0.499999999999999
        required: false
        default: null
      subjectBestHit:
        displayName: Subject Best Hit
        description: Turn on best hit per subject sequence.
        type: boolean
        required: false
        default: false
      sumStats:
        displayName: Use Sum Stats
        description: Use sum statistics.
        type: boolean
        required: false
        default: false
      xDropoffPrelimGapped:
        displayName: Preliminary Gapped Extension X-Dropoff
        description: |
          X-dropoff value (in bits) for preliminary gapped extensions.
        type: number
        format: double
        required: false
        default: null
      xDropoffFinalGapped:
        displayName: Final Gapped Extension X-Dropoff
        description: |
          X-dropoff value (in bits) for final gapped alignment.
        type: number
        format: double
        required: false
        default: null
      gapTrigger:
        displayName: Gap Trigger
        description: Number of bits to trigger gapping.
        type: number
        format: double
        required: false
        default: 22.0
      useSWTraceback:
        displayName: Use Smith-Waterman Traceback
        description: Compute locally optimal Smith-Waterman alignments?
        type: boolean
        required: false
        default: false

  DeltaBlastMatrix:
    type: string
    enum:
    - BLOSUM45
    - BLOSUM50
    - BLOSUM62
    - BLOSUM80
    - BLOSUM90
    - PAM30
    - PAM70
    - PAM250

  DeltaBlastCompBasedStats:
    type: string
    enum:
    - none
    - comp-based-stats