#%RAML 1.0 Library

types:
  # Objects
  InputBlastnConfig: !include InputBlastnConfig.raml
  InputBlastnDust:   !include InputBlastnDust.raml

  # Enums
  InputBlastnTask:          !include InputBlastnTask.raml
  InputBlastDcTemplateType: !include InputBlastnDcTemplateType.raml
