#%RAML 1.0 Library

types:
  # Objects
  IOBlastnConfig: !include IOBlastnConfig.raml
  IOBlastnDust:   !include IOBlastnDust.raml

  # Enums
  IOBlastnTask:          !include IOBlastnTask.raml
  IOBlastnDcTemplateType: !include IOBlastnDcTemplateType.raml
