#%RAML 1.0 DataType

description: |
   | Task           | Use Case                                                   |
   |----------------|------------------------------------------------------------|
   | `megablast`    | for very similar sequences (e.g, sequencing errors)        |
   | `dc-megablast` | typically used for inter-species comparisons               |
   | `blastn`       | the traditional program used for inter-species comparisons |
   | `blastn-short` | optimized for sequences less than 30 nucleotides           |
type: string
enum:
  - megablast
  - dc-megablast
  - blastn
  - blastn-short
