#!/bin/sh

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOI
  CREATE USER $QUERY_SERVICE_PG_USER WITH LOGIN PASSWORD '$QUERY_SERVICE_PG_PASS';
  CREATE USER $REPORT_SERVICE_PG_USER WITH LOGIN PASSWORD '$REPORT_SERVICE_PG_PASS';

  CREATE DATABASE $QUERY_SERVICE_PG_DB_NAME;
  CREATE DATABASE $REPORT_SERVICE_PG_DB_NAME;

  GRANT ALL PRIVILEGES ON DATABASE $QUERY_SERVICE_PG_DB_NAME TO $QUERY_SERVICE_PG_USER;
  GRANT ALL PRIVILEGES ON DATABASE $REPORT_SERVICE_PG_DB_NAME TO $REPORT_SERVICE_PG_USER;
EOI