#%RAML 1.0 DataType

uses:
  com:   ../common/index.raml
  blast: ../blast-types/blast/index.raml

type: object
additionalProperties: false
description: |
  Details about a specific job, it's configuration, and it's current status.
properties:
  id:     com.JobID
  status: com.JobStatus
  config: blast.InputBlastConfig
