#%RAML 1.0 Library

types:
  NewJobPostRequestJSON:      !include NewJobPostRequestJSON.raml
  NewJobPostRequestMultipart: !include NewJobPostRequestMultipart.raml
  NewJobPostResponse:         !include NewJobPostResponse.raml
  MetaResponse:               !include MetaResponse.raml
  GetJobResponse:             !include GetJobResponse.raml

  OutputSiteListing:  !include OutputSiteListing.raml
  OutputListOrganism: !include OutputListOrganism.raml
