#%RAML 1.0 Library

types:
  NewJobPostRequestJSON:      !include NewJobPostRequestJSON.raml
  NewJobPostRequestMultipart: !include NewJobPostRequestMultipart.raml
  NewJobPostResponse:         !include NewJobPostResponse.raml
  MetaResponse:               !include MetaResponse.raml

  LongJobResponse:  !include LongJobResponse.raml
  ShortJobResponse: !include ShortJobResponse.raml

  OutputSiteListing:  !include OutputSiteListing.raml
  OutputListOrganism: !include OutputListOrganism.raml
