#%RAML 1.0 DataType

type: object
additionalProperties: false
properties:
  organism:
    type: string
    description: Internal organism name.
  target:
    type: string
    description: Internal blast db file name.