#%RAML 1.0 DataType

uses:
  blast: ../blast-types/blast/index.raml
  ext: index.raml

type: object
additionalProperties: false
properties:
  site:
  targets:
    type: array
    items: ext.IOJobTarget
    minItems: 1
  config:
    description: |
      Blast tool configuration.

      Must be one of the following implementation types:

      - [IOBlastnConfig](#type:IOBlastnConfig)
      - [IOBlastpConfig](#type:IOBlastpConfig)
      - [IOBlastxConfig](#type:IOBlastxConfig)
      - [IOTBlastnConfig](#type:IOTBlastnConfig)
      - [IOTBlastxConfig](#type:IOTBlastxConfig)
    type: blast.IOBlastConfig
  description?:
    description: |
      User provided description of the job.
    type: string
