#%RAML 1.0 DataType

uses:
  blast: ../blast-types/blast/index.raml

type: object
additionalProperties: false
properties:
  site:
    type: string
  organism:
  target-type:
    description: |
      Target file name.  Maps to the `--db` flag for the blast tools.
    type: string
  config:
    description: |
      Blast tool configuration.

      Must be one of the following implementation types:

      - [IOBlastnConfig](#type:IOBlastnConfig)
      - [IOBlastpConfig](#type:IOBlastpConfig)
      - [IOBlastxConfig](#type:IOBlastxConfig)
      - [IOTBlastnConfig](#type:IOTBlastnConfig)
      - [IOTBlastxConfig](#type:IOTBlastxConfig)
    type: blast.IOBlastConfig
  description?:
    description: |
      User provided description of the job.
    type: string
