#%RAML 1.0 DataType

uses:
  blast: ../blast-types/blast/index.raml
  ext: index.raml

type: object
additionalProperties: false
properties:
  site:
  targets:
    type: array
    items: ext.IOJobTarget
    minItems: 1
  maxResults?:
    description: |
      Number of results to limit the search to.

      Clients sending this value must also send limiting fields such as
      `max_target_seqs`, `num_descriptions`, or `num_alignments`.

      The service will validate that the value of the limiting field(s)
      multiplied by the number of query sequences does not exceed this value.

      Assuming that the number of query seqs is represented as `Q` the
      validation is performed as `(Q * max_target_seqs) <= maxResults` or
      `(Q * max(num_descriptions, num_alignments)) <= maxResults`.
    type: integer
    minimum: 1
    required: false
  maxResultSize?:
    type: integer
    format: int64
    minimum: 0
    description: |
      Maximum number of bytes the client is willing to accept for report
      results.  If a requested report for a job is greater in size than the
      job's `maxResultSize` value, the server will return a 403 error with a
      message indicating why it is refusing the report request.

      Additionally, when requesting a report, the client may choose to override
      this value by using the `Content-Max-Length` header to provide an
      alternative max file size.

      A value of `0` indicates no size limit for generated reports.
    default: 0
  maxSequences?:
    description: |
      Maximum number of sequences allowed.

      This will alter the service's validation to only allow the specified
      number of input sequences in the posted query.
    type: integer
    format: int8
    minimum: 1
    maximum: 100
    default: 100
  config:
    description: |
      Blast tool configuration.

      Must be one of the following implementation types:

      - [IOBlastnConfig](#type:IOBlastnConfig)
      - [IOBlastpConfig](#type:IOBlastpConfig)
      - [IOBlastxConfig](#type:IOBlastxConfig)
      - [IOTBlastnConfig](#type:IOTBlastnConfig)
      - [IOTBlastxConfig](#type:IOTBlastxConfig)
    type: blast.IOBlastConfig
  description?:
    description: |
      User provided description of the job.
    type: string
  isPrimary?:
    description: |
      Set whether this job should be treated as a "primary".  Non-primary, jobs
      are hidden in the UI.
    type: boolean
    default: true