#%RAML 1.0 DataType

uses:
  io: index.raml

type: object
description: |
  The type of this response is actually just a map of site name to an array of
  blast compatible files.  The "`Site`" property defined below is a hacky
  workaround for a RAML-To-JaxRS quirk, however all properties actually present
  on the response object _will_ match the type defined by the `Site` property.
properties:
  Site:
    type: array
    items: io.OutputListOrganism
    required: false
