#%RAML 1.0 DataType

uses:
  ext: index.raml

type: object
properties:
  jobID:
    type: string
    minLength: 32
    maxLength: 32
  reportID:
    type: string
    minLength: 32
    maxLength: 32
  status:
    type: string
    enum:
      - queued
      - in-progress
      - errored
      - completed
      - expired
  config: ext.ReportReqeust
