#%RAML 1.0 DataType

uses:
  blast: ../blast-types/blast/index.raml
  b2: ../blast-types/blast-common/index.raml

type: object
properties:
  format: blast.IOBlastFormat
  fieldDelim?: string
  fields?: blast.IOBlastReportField[]
  showGIs?: boolean
  numDescriptions?: integer
  numAlignments?: integer
  lineLength?: integer
  html?: boolean
  sortHits?: b2.IOHitSorting
  sortHSPs?: b2.IOHSPSorting
  maxTargetSeqs?: integer
  parseDefLines?: boolean
