#%RAML 1.0 DataType

uses:
  com:   ../common/index.raml
  blast: ../blast-types/blast/index.raml
  ext:   index.raml

type: object
additionalProperties: false
description: |
  Details about a specific job, it's configuration, and it's current status.
properties:
  id: string
  description: string
  status: com.IOJobStatus
  created:
    type: datetime
  expires:
    type: datetime
  maxDownloadSize?: integer
  isPrimary:
    type: boolean
    description: |
      Indicates whether this job was directly run by a user as opposed to being
      a sub-job.
  parentJobs?:
    type: array
    items:
      type: object
      properties:
        id: string
        index: integer
  site: string
  targets:
    type: array
    items: ext.IOJobTarget
    minItems: 1
  isCached:
    description: |
      Indicates whether this job's data is in the service cache.  If this value
      is false, requesting a job result directly will force a synchronous
      re-run of the job to populate the cache.
    type: boolean
