#%RAML 1.0 Library

uses:
  base: ./blast/blast-cli.raml

types:
  GuestJobTransferRequest:
    displayName: Guest to User Job Transfer Request
    description: |
      Request body for a request to transfer ownership of jobs from a guest user
      to a logged in user.
    type: object
    additionalProperties: false
    properties:
      guestID:
        displayName: Guest ID
        description: ID assigned to the user before they were logged in.
        type: integer
        format: int64
        required: true

  QueryJobPostRequest:
    displayName: Query Job Request
    type: object
    additionalProperties: false
    properties:
      jobConfig:
        displayName: Job Config
        description: Job Configuration.
        type: QueryJobConfig
      blastConfig:
        displayName: Blast Tool Config
        description: |
          Blast Tool Configuration.
          
          Implemented by one of:
          
          - [BlastNConfig](#type:lib.BlastNConfig)
          - [BlastPConfig](#type:lib.BlastPConfig)
          - [BlastXConfig](#type:lib.BlastXConfig)
          - [DeltaBlastConfig](#type:lib.DeltaBlastConfig)
          - [PSIBlastConfig](#type:lib.PSIBlastConfig)
          - [RPSBlastConfig](#type:lib.RPSBlastConfig)
          - [RPSTBlastNConfig](#type:lib.RPSTBlastNConfig)
          - [TBlastNConfig](#type:lib.TBlastNConfig)
          - [TBlastXConfig](#type:lib.TBlastXConfig)
        type: base.BlastQueryConfig
      userMeta:
        displayName: User Metadata
        type: QueryJobUserMeta
        required: false
        default: null

  QueryJobPatchRequest:
    displayName: Query Job Update
    type: object
    additionalProperties: false
    properties:
      userMeta:
        displayName: User Metadata
        type: QueryJobUserMeta
        required: false
        default: null

  QueryJobConfig:
    type: object
    additionalProperties: false
    properties:
      site:
        displayName: Target Site
        type: TargetSite
      targets:
        displayName: Query Targets
        type: array
        items:
          type: QueryJobTarget
        minItems: 1
      query:
        displayName: Blast Query
        description: |
          **For Requests**
          
          Inline query definition.
          
          This field is to be used for non-file-upload blast queries.
          
          If this field is not set, a query file must be uploaded for the
          request to be valid.
          
          **For Responses**
          
          This field will be omitted.
        type: string
        required: false
      addToUserCollection:
        displayName: Add to Collection
        description: |
          Adds this job to the users collection of jobs.
          
          The user's collection of jobs is what is returned by the `/jobs`
          endpoint.
        type: boolean
        required: false
        default: false

  QueryJobUserMeta:
    type: object
    additionalProperties: false
    properties:
      summary:
        displayName: Brief Summary
        description: Brief, user defined summary or tagline for the job.
        type: string
        maxLength: 512
        required: false
      description:
        displayName: Long Description
        description: Longform, user provided description of the job.
        type: string
        required: false

  QueryJobTarget:
    type: object
    additionalProperties: false
    properties:
      targetDisplayName:
        description: Blast target display name, e.g. organism name.
        type: string
      targetFile:
        description: Target blast database file.
        type: string

  QueryJobListEntry:
    type: object
    additionalProperties: false
    properties:
      queryJobID:
        displayName: Query Job ID
        type: string
        pattern: ^[\dA-Fa-f]{32}$
        minLength: 32
        maxLength: 32
      status:
        displayName: Job Status
        type: JobStatus
      site:
        displayName: Target Site
        type: TargetSite
      createdOn:
        displayName: Created On
        description: Job creation timestamp.
        type: datetime
        required: true
      userMeta:
        displayName: User Metadata
        type: QueryJobUserMeta
        required: false

  QueryJobDetails:
    type: object
    additionalProperties: false
    properties:
      queryJobID:
        displayName: Query Job ID
        type: string
        pattern: ^[\dA-Fa-f]{32}$
        minLength: 32
        maxLength: 32
      status:
        displayName: Job Status
        type: JobStatus
      jobConfig:
        displayName: Job Config
        description: Job Configuration.
        type: QueryJobConfig
      blastConfig:
        displayName: Blast Tool Config
        description: |
          Blast Tool Configuration.
          
          Implemented by one of:
          
          - [BlastNConfig](#type:lib.BlastNConfig)
          - [BlastPConfig](#type:lib.BlastPConfig)
          - [BlastXConfig](#type:lib.BlastXConfig)
          - [DeltaBlastConfig](#type:lib.DeltaBlastConfig)
          - [PSIBlastConfig](#type:lib.PSIBlastConfig)
          - [RPSBlastConfig](#type:lib.RPSBlastConfig)
          - [RPSTBlastNConfig](#type:lib.RPSTBlastNConfig)
          - [TBlastNConfig](#type:lib.TBlastNConfig)
          - [TBlastXConfig](#type:lib.TBlastXConfig)
        type: base.BlastQueryConfig
      createdOn:
        displayName: Created On
        description: Job creation timestamp.
        type: datetime
        required: true
      userMeta:
        displayName: User Metadata
        type: QueryJobUserMeta
        required: false
      subJobs:
        displayName: Sub-Job IDs
        description: List of IDs of sub-jobs that belong to this job.
        type: array
        items:
          type: string
          pattern: ^[\dA-Fa-f]{32}$
          minLength: 32
          maxLength: 32
        minItems: 1
        required: false

  JobBulkStatusResponse:
    displayName: Bulk Job Status Response
    description: |
      Returns a mapping of job-id to status for each of the valid job IDs that
      appeared in the original bulk status request.
    type: object
    properties:
      /^[\dA-Fa-f]{32}$/:
        type: JobStatus

  JobCreateResponse:
    displayName: Job Creation Response
    description: |
      Response body returned on the successful creation of a new BLAST query
      job.
    type: object
    additionalProperties: false
    properties:
      queryJobID:
        displayName: Query Job ID
        type: string
        pattern: ^[\dA-Fa-f]{32}$
        minLength: 32
        maxLength: 32

  JobStatus:
    type: string
    enum:
    - queued
    - in-progress
    - complete
    - failed
    - expired

  TargetSite:
    type: string
    enum:
    - AmoebaDB
    - CryptoDB
    - FungiDB
    - GiardiaDB
    - HostDB
    - MicrosporidiaDB
    - PiroplasmaDB
    - PlasmoDB
    - ToxoDB
    - TrichDB
    - TriTrypDB
    - VectorBase
    - VEuPathDB

  BlastTargetIndex:
    type: object
    properties:
      /^\w+$/:
        type: BlastTargetMap

  BlastTargetMap:
    type: object
    properties:
      /^\w+$/:
        type: BlastableTarget

  BlastableTarget:
    type: object
    additionalProperties: false
    properties:
      naTargets:
        type: array
        items:
          type: string
        required: false
        default: []
      aaTargets:
        type: array
        items:
          type: string
        required: false
        default: []
