#%RAML 1.0 Extension

extends: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.0.1/libraries/base-service.raml

title: Multi-Blast Service
version: 1.0.0
mediaType: application/json

uses:
  error: https://raw.githubusercontent.com/VEuPathDB/docs-api-schema/v2.0.1/libraries/errors.raml
  lib: schema/library.raml

securitySchemes:
  header-auth:
    description: Authentication based on a WDK auth cookie.
    type:
      x-custom
    describedBy:
      headers:
        Auth_Key:
          description: Authorization header.
          type: string


#
# Example Endpoints
#

/:
  displayName: Job Management
  post:
    displayName: Create Jobs
    body:
      application/json: lib.NewJobPostRequestJSON
      multipart/form-data: lib.NewJobPostRequestMultipart

/meta:
  displayName: Service Information
  get:
    displayName: Get Service Meta
    responses:
      200:
        body: lib.MetaGetResponse
      401:
        body: error.UnauthorizedError
      500:
        body: error.ServerError

/{job-id}:
  displayName: Job Lookup
  uriParameters:
    job-id: lib.JobId

  get:
    displayName: Get Job
    responses:
      200:
        body:
      401:
        body: error.UnauthorizedError
      500:
        body: error.ServerError

  /report:
    displayName: Get Job Report
    get:
      responses:
        200:
          headers:
            Content-Disposition:
              type: string
              pattern: 'attachment; filename="([^"]+)"'
          body:
            text/plain: object
            application/json: object
            application/xml: object
            application/octet-stream: object
        401:
          body: error.UnauthorizedError
        500:
          body: error.ServerError
