#%RAML 1.0 Library

types:
  JobGetResponse:
    type: object
    additionalProperties: false
    properties:
      jobId: JobId
      createdOn:
        type: datetime-only
      expiresOn:
        type: datetime-only
      expiresIn: JobExpiration

  JobExpiration:
    type: object
    additionalProperties: false
    properties:
      days:
        type: integer
        format: int8
      hours:
        type: integer
        format: int8
      minutes:
        type: integer
        format: int8
      seconds:
        type: integer
        format: int8

  MetaGetResponse:
    type: object
    additionalProperties: false
    properties:
      blastFiles:
        type: MetaResponseBlastFile[]

  MetaResponseBlastFile:
    type: object
    additionalProperties: false
    properties:
      organism:
        type: string
      fileType:
        type: string

  NewJobPostRequestJSON:
    type: object
    additionalProperties: false
    properties:
      query?:
        description: |
          Gene sequences or gene ID lookup.

          If a search file is uploaded, this field will be ignored.
          If a search file is **not** uploaded, this field will be required.
        type: string
      description: string
      tool: InputTool
      defaults: NewJobConfigFormat
      options: NewJobToolOptions

  NewJobPostRequestMultipart:
    type: object
    additionalProperties: false
    properties:
      file: file
      jsonParams: NewJobPostRequestJSON

  NewJobToolOptions:
    type: object
    additionalProperties: false
    properties:
      useComplexityMasking: boolean
      resultsPerQueryPerDatabase?:
        type: integer
        format: int32
        minimum: 1
        maximum: 500
        default: 10
      maxEValue: InputMaxEVal
      sortHits?: InputHitSorting
      sortHsps?: InputHSPSorting
      wordSize?:
        type: integer
        format: int8
        minimum: 2
        maximum: 60
        default: 11
      nucleotide?:
        type: array
        items: InputNucleotideOpt
        uniqueItems: true
      peptide?:
        type: array
        items: InputPeptideOpt
        uniqueItems: true

  NewJobConfigFormat:
    description: Job report configuration options.
    type: object
    additionalProperties: false
    properties:
      format: InputFormat
      delimiter?:
        description: |
          Custom delimiter for the `csv`, `tabular` and `tabular-with-comments`
          output formats.

          Defaults to the tab character for `tabular` and
          `tabular-with-comments`.

          Defaults to a comma for `csv`.

          If specified for formats other than `csv`, `tabular` or
          `tabular-with-comments` this field will be ignored.
        type: string
        maxLength: 1
        minLength: 1
      fields:
        description: |
          Custom field selection for the `csv`, `tabular` and
          `tabular-with-comments` output formats.

          Entries in this array will appear in the defined order in the output.
        type: InputBlastField[]
        default:
          - qaccver
          - saccver
          - pident
          - length
          - mismatch
          - gapopen
          - qstart
          - qend
          - sstart
          - send
          - evalue
          - bitscore

  ##############################################################################
  #
  #     Enum Types
  #
  ##############################################################################

  InputHitSorting:
    description: |
      Sorting option for hits.

      Alignment view options:

      1. Sort by evalue,
      2. Sort by bit score,
      3. Sort by total score,
      4. Sort by percent identity,
      5.  Sort by query coverage

      Only applicable for the following formats:

      1. Pairwise
      2. Query-anchored showing identities
      3. Query-anchored no identities
      4. Flat query-anchored showing identities
      5. Flat query-anchored no identities
    type: string
    enum:
      - by-evalue
      - by-bit-score
      - by-total-score
      - by-percent-identity
      - by-query-coverage

  InputHSPSorting:
    description: |
      Sorting option for hps:

      1. Sort by hsp evalue,
      2. Sort by hsp score,
      3. Sort by hsp query start,
      4. Sort by hsp percent identity,
      5. Sort by hsp subject start

      Only applicable for the Pairwise format type.
    type: string
    enum:
      - by-evalue
      - by-score
      - by-query-start
      - by-percent-identity
      - by-subject-start

  InputScoringMatrix:
    type: string
    enum:
      - blosum45
      - blosum50
      - blosum62
      - blosum80
      - blosum90
      - pam250
      - pam30
      - pam70

  InputFormat:
    description: |
      0  = Pairwise,
      1  = Query-anchored showing identities,
      2  = Query-anchored no identities,
      3  = Flat query-anchored showing identities,
      4  = Flat query-anchored no identities,
      5  = BLAST XML,
      6  = Tabular,
      7  = Tabular with comment lines,
      8  = Seqalign (Text ASN.1),
      9  = Seqalign (Binary ASN.1),
      10 = Comma-separated values,
      11 = BLAST archive (ASN.1),
      12 = Seqalign (JSON),
      13 = Multiple-file BLAST JSON,
      14 = Multiple-file BLAST XML2,
      15 = Single-file BLAST JSON,
      16 = Single-file BLAST XML2,
      17 = Sequence Alignment/Map (SAM),
      18 = Organism Report
    type: string
    enum:
      - pairwise
      - query-anchored-with-identities
      - query-anchored-wo-identities
      - flat-query-anchored-with-identities
      - flat-query-anchored-wo-identities
      - xml
      - tabular
      - tabular-with-comments
      - text-asn-1
      - binary-asn-1
      - csv
      - blast-archive-asn-1
      - seqalign-json
      - multi-file-json
      - multi-file-xml2
      - single-file-json
      - single-file-xml2
      - sam
      - org-report

  InputMaxEVal:
    type: string
    enum:
      - "100000"
      - "10000"
      - "1000"
      - "100"
      - "10"
      - "1"
      - "1e-3"
      - "1e-5"
      - "1e-10"
      - "1e-20"
      - "1e-40"
      - "1e-80"
    default: "10"

  InputPeptideOpt:
    description: |
      Only valid for the following tools:

      1. blastp
      2. blastx

      If the selected tool is not one of the above, this field will be ignored.
    type: string
    enum:
      - peptides
      - assembled-proteome

  InputNucleotideOpt:
    description: |
      Only valid for the following tools:

      1. blastn
      2. tblastn
      3. tblastx

      If the selected tool is not one of the above, this field will be ignored.
    type: string
    enum:
      - contigs
      - ests
      - scaffolds
      - transcripts
      - chromosomes
      - assembled-transcriptome

  InputBlastSAMFormat:
    description: |
      Options for the `sam` (Sequence Alignment/Map) report format.
    type: string
    enum:
      - include-sequence-data
      - subject-as-ref-seq

  InputBlastField:
    description: |
      Custom report format fields.

      These fields only apply to the following report formats:

      * `tabular`
      * `tabular-with-comments`
      * `csv`

      Format definitions:

      * `qseqid`: Query Seq-id
      * `qgi`: Query GI
      * `qacc`: Query accesion
      * `qaccver`: Query accesion.version
      * `qlen`: Query sequence length
      * `sseqid`: Subject Seq-id
      * `sallseqid`: All subject Seq-id(s), separated by a ';'
      * `sgi`: Subject GI
      * `sallgi`: All subject GIs
      * `sacc`: Subject accession
      * `saccver`: Subject accession.version
      * `sallacc`: All subject accessions
      * `slen`: Subject sequence length
      * `qstart`: Start of alignment in query
      * `qend`: End of alignment in query
      * `sstart`: Start of alignment in subject
      * `send`: End of alignment in subject
      * `qseq`: Aligned part of query sequence
      * `sseq`: Aligned part of subject sequence
      * `evalue`: Expect value
      * `bitscore`: Bit score
      * `score`: Raw score
      * `length`: Alignment length
      * `pident`: Percentage of identical matches
      * `nident`: Number of identical matches
      * `mismatch`: Number of mismatches
      * `positive`: Number of positive-scoring matches
      * `gapopen`: Number of gap openings
      * `gaps`: Total number of gaps
      * `ppos`: Percentage of positive-scoring matches
      * `frames`: Query and subject frames separated by a '/'
      * `qframe`: Query frame
      * `sframe`: Subject frame
      * `btop`: Blast traceback operations (BTOP)
      * `staxid`: Subject Taxonomy ID
      * `ssciname`: Subject Scientific Name
      * `scomname`: Subject Common Name
      * `sblastname`: Subject Blast Name
      * `sskingdom`: Subject Super Kingdom
      * `staxids`: unique Subject Taxonomy ID(s), separated by a ';' (in numerical order)
      * `sscinames`: unique Subject Scientific Name(s), separated by a ';'
      * `scomnames`: unique Subject Common Name(s), separated by a ';'
      * `sblastnames`: unique Subject Blast Name(s), separated by a ';' (in alphabetical order)
      * `sskingdoms`: unique Subject Super Kingdom(s), separated by a ';' (in alphabetical order)
      * `stitle`: Subject Title
      * `salltitles`: All Subject Title(s), separated by a '<>'
      * `sstrand`: Subject Strand
      * `qcovs`: Query Coverage Per Subject
      * `qcovhsp`: Query Coverage Per HSP
      * `qcovus`: Query Coverage Per Unique Subject (blastn only)
      ```
    type: string
    enum:
      - qseqid
      - qgi
      - qacc
      - qaccver
      - qlen
      - sseqid
      - sallseqid
      - sgi
      - sallgi
      - sacc
      - saccver
      - sallacc
      - slen
      - qstart
      - qend
      - sstart
      - send
      - qseq
      - sseq
      - evalue
      - bitscore
      - score
      - length
      - pident
      - nident
      - mismatch
      - positive
      - gapopen
      - gaps
      - ppos
      - frames
      - qframe
      - sframe
      - btop
      - staxid
      - ssciname
      - scomname
      - sblastname
      - sskingdom
      - staxids
      - sscinames
      - scomnames
      - sblastnames
      - sskingdoms
      - stitle
      - salltitles
      - sstrand
      - qcovs
      - qcovhsp
      - qcovus

  InputTool:
    type: string
    enum:
      - blastn
      - blastp
      - blastx
      - tblastn
      - tblastx

  ##############################################################################
  #
  #     Common Types
  #
  ##############################################################################

  JobId:
    description: 128bit UUID encoded in Base62.
    type: string
    maxLength: 22
    minLength: 11
