#%RAML 1.0 Library

uses:
  blast: blast-types.raml

types:
  ReportJobRequest:
    type: object
    additionalProperties: false
    properties:
      queryJobID:
        type: string
        minLength: 32
        maxLength: 32
        pattern: '^[\dA-Fa-f]{32}$'
        required: true
      blastConfig:
        type: blast.BlastFormatConfig
        required: false
        default:
          formatType: pairwise
      meta:
        type: ReportJobMeta
        required: false
        default: null

  ReportJobDetails:
    type: object
    additionalProperties: false
    properties:
      reportJobID:
        displayName: Report Job ID
        type: string
        minLength: 32
        maxLength: 32
        pattern: '^[\dA-Fa-f]{32}$'
        required: true
      queryJobID:
        displayName: Query Job ID
        type: string
        minLength: 32
        maxLength: 32
        pattern: '^[\dA-Fa-f]{32}$'
        required: true
      status:
        displayName: Job Status
        type: JobStatus
        required: true
      blastConfig:
        type: blast.BlastFormatConfig
        required: true
      meta:
        type: ReportJobMeta
        required: false
        default: null

  ReportJobListEntry:
    type: object
    additionalProperties: false
    properties:
      reportJobID:
        displayName: Report Job ID
        type: string
        minLength: 32
        maxLength: 32
        pattern: '^[\dA-Fa-f]{32}$'
        required: true
      queryJobID:
        displayName: Query Job ID
        type: string
        minLength: 32
        maxLength: 32
        pattern: '^[\dA-Fa-f]{32}$'
        required: true
      status:
        displayName: Job Status
        type: JobStatus
        required: true
      meta:
        displayName: Job Meta
        type: ReportJobMeta
        required: false
        default: null

  ReportJobMeta:
    type: object
    additionalProperties: false
    properties:
      summary:
        type: string
        required: false
        default: null
      description:
        type: string
        required: false
        default: null

  FileEntry:
    type: object
    additionalProperties: false
    properties:
      name:
        displayName: File Name
        type: string
        required: true
      size:
        displayName: File Size
        description: Size of the file in bytes.
        type: integer
        format: long
        required: true

  JobStatus:
    type: string
    enum:
    - queued
    - in-progress
    - complete
    - failed
    - expired