= MultiBlast Developer Info
:source-highlighter: highlightjs
:toc:
:toclevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Developing the Service

=== Prerequisites

The following tools are required or strongly recommended for developers working
on the MultiBlast stack.

* link:https://www.docker.com/[Docker]
* link:https://docs.docker.com/compose/install/[Docker Compose Plugin]
* link:https://www.gnu.org/software/make/[Make]
* link:https://nodejs.org/en/[Node & NPM]
* link:https://openjdk.org/projects/jdk/[Java 18+]

=== Gradle Tasks

The following are root level gradle tasks that operate on the entire project.

Each of the following tasks may be executed by passing the name of the task to
the `./gradlew` command.

[NOTE]
====
This list does not include the available default gradle tasks such as `build` or
`test`.

For a full listing of available gradle tasks, run `./gradlew tasks` in the repo
root.
====

`generate-raml-docs`::
Generates HTML documentation of the service APIs based on the RAML API
definitions in each subproject and puts the output in the `docs` directory.
+
.Example
[source, bash]
----
./gradlew generate-raml-docs
----

`generate-jaxrs`::
Generates JaxRS based Java code from the service API RAML definitions in each
subproject.
+
.Example
[source, bash]
----
./gradlew generate-jaxrs
----

`compose-build`::
See <<Build>>.

`compose-up`::
See <<In The Background,Run>>.

`compose-stop`::
See <<Stop>>.

`compose-down`::
See <<Teardown>>.

`download-blast-dbs`::
Attempts to download several example BLAST databases from the configured remote
server over SFTP.
+
On first run, this task will fail and will create a file named
`mblast-dev.properties`.  The created file should be edited with your details,
then the task can be re-run.
+
NOTE: This task is automatically called by `compose-up` and shouldn't need to be
called directly.
+
.Example
[source, bash]
----
./gradlew download-blast-dbs
----

== Running Locally


=== Prerequisites


==== General Local Deployment Requirements

Follow the steps under the "Prerequisites" heading in the VEuPathDB Confluence
document "Deploy Containerized Services for Local Development".


==== Multi-Blast Specific Requirements

Before the Multi-Blast service can be spun up locally, your local environment
must have target BLAST+ database files from the VEuPathDB servers.

To download these files, please follow these instructions:

===== 1. Generate a `mblast-dev.properties` file.

If you do not already have this file in the root of the project repo, then a new
one can be generated by running the command:

[source, bash]
----
./gradlew download-blast-dbs
----

The executed Gradle task will exit with an error, but will create a basic
`mblast-dev.properties` file.

.Example Command Output
[%collapsible]
====
[source]
----
> Task :download-blast-dbs FAILED

Blast DB directory does not exist, download blast files...


Missing required properties file `mblast-dev.properties`.


File created, please edit this file with the correct configuration values and rerun this task.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':download-blast-dbs'.
> java.lang.RuntimeException (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 476ms
4 actionable tasks: 1 executed, 3 up-to-date
----
====

===== 2. Populate the `mblast-dev.properties` file.

The freshly generated `mblast-dev.properties` file should resemble the
following:

[source, properties]
----
ssh.user=ellie
ssh.host=some.ssh.server.org
ssh.port=21

site.name=PlasmoDB
site.build=build-59

files.root=/var/www/Common/apiSiteFilesMirror/webServices
----

This file will need to be edited with the following details:

[cols="1m,7"]
|===
| ssh.user
| The user name you normally use when connecting to the VEuPathDB servers.

| ssh.host
| The target server from which you will download BLAST+ databases.

| ssh.port
| The port number to connect to the target server using.

| site.name
| Name or Project ID of the site for which BLAST+ database files will be
downloaded.

| site.build
| The current site build value.

| files.root
| Path to the web services content root directory.

|===

===== 3. Download the BLAST+ database files.

Once the `mblast-dev.properties` file has been configured, the following command
may be run again to download the BLAST+ database files.

[source, bash]
----
./gradlew download-blast-dbs
----

.Example Command Output
[%collapsible]
====
[source]
----
> Task :download-blast-dbs

Blast DB directory does not exist, download blast files...
  Connecting to some.ssh.server.org:21 over SSH
  Listing available organisms...
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism1/blast/Organism1ESTs.nhr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism1/blast/Organism1ESTs.nsq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism1/blast/Organism1ESTs.nin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism2/blast/Organism2Genome.nsq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism2/blast/Organism2AnnotatedProteins.psq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism2/blast/Organism2Genome.nin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism2/blast/Organism2AnnotatedProteins.phr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism2/blast/Organism2AnnotatedCDSs.nsq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism2/blast/Organism2AnnotatedTranscripts.nin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism2/blast/Organism2AnnotatedTranscripts.nhr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism2/blast/Organism2AnnotatedCDSs.nin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism2/blast/Organism2AnnotatedTranscripts.nsq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism2/blast/Organism2AnnotatedProteins.pin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism2/blast/Organism2AnnotatedCDSs.nhr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism2/blast/Organism2Genome.nhr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism3/blast/Organism3AnnotatedTranscripts.nin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism3/blast/Organism3AnnotatedTranscripts.nhr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism3/blast/Organism3AnnotatedTranscripts.nsq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism3/blast/Organism3Genome.nsq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism3/blast/Organism3AnnotatedCDSs.nsq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism3/blast/Organism3AnnotatedCDSs.nin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism3/blast/Organism3AnnotatedProteins.pin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism3/blast/Organism3AnnotatedCDSs.nhr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism3/blast/Organism3AnnotatedProteins.phr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism3/blast/Organism3Genome.nin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism3/blast/Organism3Genome.nhr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism3/blast/Organism3AnnotatedProteins.psq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism4/blast/Organism4Genome.nhr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism4/blast/Organism4Genome.nin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism4/blast/Organism4AnnotatedProteins.pin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism4/blast/Organism4AnnotatedTranscripts.nhr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism4/blast/Organism4AnnotatedTranscripts.nsq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism4/blast/Organism4AnnotatedProteins.phr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism4/blast/Organism4AnnotatedCDSs.nsq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism4/blast/Organism4Genome.nsq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism4/blast/Organism4AnnotatedTranscripts.nin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism4/blast/Organism4AnnotatedCDSs.nhr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism4/blast/Organism4AnnotatedCDSs.nin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism4/blast/Organism4AnnotatedProteins.psq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism5/blast/Organism5Genome.nin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism5/blast/Organism5AnnotatedProteins.psq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism5/blast/Organism5AnnotatedTranscripts.nsq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism5/blast/Organism5AnnotatedProteins.pin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism5/blast/Organism5Genome.nsq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism5/blast/Organism5AnnotatedTranscripts.nin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism5/blast/Organism5AnnotatedCDSs.nhr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism5/blast/Organism5AnnotatedTranscripts.nhr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism5/blast/Organism5AnnotatedProteins.phr
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism5/blast/Organism5AnnotatedCDSs.nsq
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism5/blast/Organism5AnnotatedCDSs.nin
  downloading file /var/www/Common/apiSiteFilesMirror/webServices/PlasmoDB/build-60/Organism5/blast/Organism5Genome.nhr

BUILD SUCCESSFUL in 20s
4 actionable tasks: 2 executed, 2 up-to-date
----
====

=== Build

Builds the development docker compose stack.

[source, shell]
----
./gradlew compose-build
----


=== Run


==== In The Background

Spins up the docker compose stack in the background.

[source, shell]
----
./gradlew compose-up
----

Tailing the logs for a specific background container can be done by using the
following command:

[source, shell]
----
docker logs --follow ${CONTAINER_NAME} <1>
----
<1> `CONTAINER_NAME` may be one of:
+
* `mblast-minio-1`
* `mblast-minio-create-buckets`
* `mblast-queue-1`
* `mblast-queue-db-1`
* `mblast-query-service-1`
* `mblast-report-service-1`

WARNING: `sudo` may be required to run `docker` commands in your environment.

==== In The Foreground

Manually spin up the docker compose stack in the console foreground.

[source, shell]
----
cd docker-compose
docker compose -f docker-compose.yml -f docker-compose.dev.yml up
----


=== Stop

Shuts down a running development docker compose stack without removing the
containers.

[source, shell]
----
./gradlew compose-stop
----


=== Teardown

Shuts down and/or removes the containers for the development docker compose
stack.

[source, shell]
----
./gradlew compose-down
----
