= MultiBlast Developer Info
:toc:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Developing the Service

=== Prerequisites

The following tools are required or strongly recommended for developers working
on the MultiBlast stack.

* link:https://www.docker.com/[Docker]
* link:https://docs.docker.com/compose/install/[Docker Compose Plugin]
* link:https://www.gnu.org/software/make/[Make]
* link:https://nodejs.org/en/[Node & NPM]
* link:https://openjdk.org/projects/jdk/[Java 18+]

=== Gradle Tasks

The following are root level gradle tasks that operate on the entire project.

Each of the following tasks may be executed by passing the name of the task to
the `./gradlew` command.

[NOTE]
====
This list does not include the available default gradle tasks such as `build` or
`test`.

For a full listing of available gradle tasks, run `./gradlew tasks` in the repo
root.
====

`generate-raml-docs`::
Generates HTML documentation of the service APIs based on the RAML API
definitions in each subproject and puts the output in the `docs` directory.
+
.Example
[source, bash]
----
./gradlew generate-raml-docs
----

`generate-jaxrs`::
Generates JaxRS based Java code from the service API RAML definitions in each
subproject.
+
.Example
[source, bash]
----
./gradlew generate-jaxrs
----

`compose-build`::
See <<Build>>.

`compose-up`::
See <<In The Background,Run>>.

`compose-stop`::
See <<Stop>>.

`compose-down`::
See <<Teardown>>.

`download-blast-dbs`::
Attempts to download several example BLAST databases from the configured remote
server over SFTP.
+
On first run, this task will fail and will create a file named
`mblast-dev.properties`.  The created file should be edited with your details,
then the task can be re-run.
+
NOTE: This task is automatically called by `compose-up` and shouldn't need to be
called directly.
+
.Example
[source, bash]
----
./gradlew download-blast-dbs
----

== Running Locally

=== Prerequisites

TODO: Setup sshuttle

TODO: gradle.properties OR direnv

Setup local blastdb path::
. Create a local directory in the project root named `blastdb`
. In the `blastdb` directory, create a directory structure mirroring the
structure of the remote `webServices` directory for your target site(s) and
build number.
. Use SFTP or some other tool to download target databases for local use.
+
----
service-multi-blast/
  |- blastdb/
       |- PlasmoDB/
            |- build-59/
                 |- Pfalciparum/
                 |    |- SomeTarget.nhr
                 |    |- SomeTarget.nin
                 |    |- SomeTarget.nsq
----


=== Build

Builds the development docker compose stack.

[source, shell]
----
./gradlew compose-build
----


=== Run


==== In The Background

Spins up the docker compose stack in the background.

[source, shell]
----
./gradlew compose-up
----

Tailing the logs for a specific background container can be done by using the
following command:

[source, shell]
----
docker logs --follow ${CONTAINER_NAME} <1>
----
<1> `CONTAINER_NAME` may be one of:
+
* `mblast-minio-1`
* `mblast-minio-create-buckets`
* `mblast-queue-1`
* `mblast-queue-db-1`
* `mblast-query-service-1`
* `mblast-report-service-1`

WARNING: `sudo` may be required to run `docker` commands in your environment.

==== In The Foreground

Manually spin up the docker compose stack in the console foreground.

[source, shell]
----
cd docker-compose
docker compose -f docker-compose.yml -f docker-compose.dev.yml up
----


=== Stop

Shuts down a running development docker compose stack without removing the
containers.

[source, shell]
----
./gradlew compose-stop
----


=== Teardown

Shuts down and/or removes the containers for the development docker compose
stack.

[source, shell]
----
./gradlew compose-down
----


=== Accessing the Service

The development docker compose stack includes a Traefik instance which will make
the MultiBlast Service APIs available under the singular URL
link:http://mblast.local.apidb.org[].

The individual services are published under this URL at `/query` for the query
service and `/report` for the report service.


== Environment Variables


=== Example `.env` Contents

[source, shell]
----
POSTGRES_WATCHTOWER=false
QUERY_SERVICE_WATCHTOWER=false

TRAEFIK_ENTRYPOINTS=local
TRAEFIK_MBLAST_HOST=mblast.local.apidb.org
TRAEFIK_QUERY_ROUTER=mblast-query-dev
TRAEFIK_REPORT_ROUTER=mblast-report-dev


MBLAST_QUERY_SERVICE_TAG=latest
MBLAST_QUEUE_DB_TAG=latest
MBLAST_REPORT_SERVICE_TAG=latest


AUTH_SECRET_KEY=


REPORT_SERVER_PORT=8080
QUERY_SERVER_PORT=8080


BLAST_DB_MOUNT_SOURCE=../blastdb
BLAST_DB_MOUNT_TARGET=/blastdb
SITE_BUILD_DIR=build-59


LDAP_SERVERS=

ORACLE_BASE_DN=

ACCT_DB_TNS_NAME=
ACCT_DB_USER=
ACCT_DB_PASS=
ACCT_DB_POOL_SIZE=5

USER_DB_TNS_NAME=
USER_DB_USER=
USER_DB_PASS=
USER_DB_POOL_SIZE=5


POSTGRES_PORT=5432
POSTGRES_ROOT_PASS=dbrootuser
POSTGRES_ROOT_USER=dbrootpass

QUERY_SERVICE_PG_DB_NAME=query
QUERY_SERVICE_PG_USER=querypguser
QUERY_SERVICE_PG_PASS=querypgpass
QUERY_SERVICE_PG_POOL_SIZE=10

REPORT_SERVICE_PG_DB_NAME=report
REPORT_SERVICE_PG_USER=reportpguser
REPORT_SERVICE_PG_PASS=reportpgpass
REPORT_SERVICE_PG_POOL_SIZE=10


S3_ACCESS_TOKEN=miniouser
S3_HOST=minio
S3_PORT=9000
S3_SECRET_KEY=miniopass
S3_USE_HTTPS=false

QUERY_SERVICE_S3_BUCKET=mblast-query-jobs

REPORT_SERVICE_S3_BUCKET=mblast-report-jobs

JOB_CACHE_TIMEOUT_DAYS=30


RABBITMQ_ROOT_USER=rabbitmquser
RABBITMQ_ROOT_PASS=rabbitmqpass
RABBITMQ_PORT=5672

QUERY_SERVICE_QUEUE_NAME_1=primary-queries
QUERY_SERVICE_QUEUE_NAME_2=secondary-queries
QUERY_SERVICE_QUEUE_POOL_SIZE=5

REPORT_SERVICE_QUEUE_NAME=report-jobs
REPORT_SERVICE_QUEUE_POOL_SIZE=5


MAX_NA_SEQ_SIZE=1048576
MAX_AA_SEQ_SIZE=102400
MAX_INPUT_QUERY_SIZE=3145728
MAX_SEQUENCES_PER_JOB=100
MAX_RESULTS_PER_QUERY=10000
----
