= Multi-Blast Service
:toc: left

== Goal

Expose an API allowing users to submit multi-sequence blast
queries against one or more VEuPathDB blast databases and
view/download the result in any of the blast+ supported
formats.

Additionally, due to the time and processor cost of running
these queries, the API should cache results and only ever
run unique or expired queries.  Multiple requests with
identical configurations should only result in 1 job being
created and cached.

== Architecture

The multi-blast project (mblast) consists of 6 Docker
containers and 2 volumes.  Additionally the project depends
on tables in an Oracle "user DB".

image::assets/network.svg[]

Of the 6 containers, only 1 is exposed publicly and handles
all communications with external clients.  The remaining
containers communicate internally on a Docker managed
private network.

The containers are:

. The publicly exposed HTTP server
. A job queue server (https://github.com/fireworq/fireworq[Fireworq])
. A queue persistance database (MySQL)
. 2 NCBI/Blast containers with internal HTTP services
. A blast config validation service

The volumes used are 1 shared volume containing the mblast
workspaces, and 1 mounted filesystem containing the target
blast databases.

=== Containers

==== Public HTTP Server

This container is the root or primary service for the
project and orchestrates the operations for the other
services.

The responsibilities for this service include:

* Authenticating user requests
* Applying VEuPathDB specific validation to blast configurations.
* Submitting jobs to the Fireworq queue.
* Reading and writing data from/to the Oracle user DB.

===== Exposed Endpoints

https://veupathdb.github.io/service-multi-blast/api.html[Full API Documentation]

.Endpoint Overview
[cols="2m,1m,4"]
|===
| Endpoint | Method | Purpose

| /api
| GET
| Prints API Docs

| /health
| GET
| Prints service health

| /jobs
| GET\|POST
| List or create blast jobs

| /jobs/{:jobID}
| GET\|POST
| View or rerun an individual blast job

| /jobs/{:jobID}/query
| GET
| Retrieve a blast job's query text

| /meta
| GET
| Prints a tree of available target Blast DBs

| /metrics
| GET
| Prints https://prometheus.io/[Prometheus] service metrics

| /reports
| GET\|POST
| List or create report jobs

| /reports/{:jobID}
| GET\|POST
| View or rerun an individual report job

| /reports/{:jobID}/files/{:filename}
| GET
| View or download a generated report
|===

==== "Blast" Server

The blast container is based on the
https://hub.docker.com/r/ncbi/blast[`ncbi/blast` Docker image]
and is extended with a simple HTTP server that accepts a
configuration via a `POST` request and returns a Fireworq
compatible response.

The server translates the posted configuration into a CLI
call to a target blast+ CLI tool with all output stored in a
job specific workspace.

===== Internal Endpoints

https://veupathdb.github.io/service-multi-blast/querier-api.html[Full API Documentation]

.Endpoint Overview
[cols="2m,1m,4"]
|===
| Endpoint | Method | Purpose

| /blast
| POST
| Run a blast+ tool with the given configuration

| /metrics
| GET
| Prints https://prometheus.io/[Prometheus] service metrics

|===

==== "Formatter" Server

The formatter container is based on the
https://hub.docker.com/r/ncbi/blast[`ncbi/blast` Docker image]
and is extended with a simple HTTP server that accepts a
configuration via a `POST` request and returns a Fireworq
compatible response.

The server translates the posted configuration into a CLI
call to `blast_formatter` run against the blast results
present in the job specific workspace.  All output is stored
in a subdirectory of that workspace.

===== Internal Endpoints

https://veupathdb.github.io/service-multi-blast/formatter-api.html[Full API Documentation]

.Endpoint Overview
[cols="2m,1m,4"]
|===
| Endpoint | Method | Purpose

| /report
| POST
| Runs `blast_formatter` with the given config
|===

==== Validation Server

A simple server that validates the POSTed configuration
against the rules outlined in the blast+ tool help
documentation.

==== Queue Server

The queue container is a custom image that pulls in a target
Fireworq version along with a
https://github.com/VEuPathDB/util-fireworq-init[custom initialization tool]
that ensures the job queues are set up correctly.

==== Queue DB

A small MySQL server managed by Fireworq.  This DB is
populated on init by the scripts in `./databases/queue/ddl`
in the repository root.

=== Database

In addition to the 6 containers the mblast project also uses
several tables currently parked in the Oracle user DB.

The definitions for these tables can be found in
`./databases/wdk/user-tables.sql`.

.`multiblast_jobs`
[%collapsible]
====
Root blast job table.

[cols="1m,1m,4"]
|===
| Column | Type | Purpose

| job_digest
| byte[16]
| Primary key (digest of the job configuration)

| job_config
| clob
| Parsed job configuration

| query
| clob
| input query string

| queue_id
| int(7)
| ID of the job in the Fireworq queue.  This value is
  updated when jobs are re-run.

| project_id
| varchar(16)
| Project ID for the site the job was run on.

| status
| varchar(10)
| Last known status for the job.  This value is updated only
  when a client requests info about a job from the service. +
  **WARNING**: This column is for internal service usage and
  cannot be used to accurately derive overall assessments.
  For example, it is a normal case for this field to
  indicate that a job is "queued" when in reality the job
  has completed or failed.

| created_on
| timestamptz
| Timestamp for the job creation.

| delete_on
| timestamptz
| (DEPRECATED) timestamp for when the job will "expire".
  This column is not currently used and should be dropped in
  a later update.
|===
====

.`multiblast_job_to_targets`
[%collapsible]
====
Table linking mblast jobs to target blast DBs.

[cols="1m,1m,4"]
|===
| Column | Type | Purpose

| job_digest
| byte[16]
| Foreign key to `multiblast_jobs.job_digest`

| organism
| varchar(256)
| Organism name WDK internal value

| target_file
| varchar(256)
| Target blast DB
|===
====

.`multiblast_job_to_jobs`
[%collapsible]
====
Table linking mblast jobs to one another (job hierarchy).

[cols="1m,1m,4"]
|===
| Column | Type | Purpose

| job_digest
| byte[16]
| Child job digest. Foreign key to `multiblast_jobs.job_digest`

| parent_digest
| byte[16]
| Parent job digest. Foreign key to `multiblast_jobs.job_digest`

| position
| int(4)
| Position of a child job under it's parent job.
|===
====

.`multiblast_users`
[%collapsible]
====
Table linking users to mblast jobs.  (More than one user may
be linked to a single job).

[cols="1m,1m,4"]
|===
| Column | Type | Purpose

| job_digest
| byte[16]
| Foreign key to `multiblast_jobs.job_digest`

| user_id
| int(12)
| WDK Site user ID.

| description
| varchar(1024)
| User provided description for the job this record links
  to.

| max_download_size
| int(12)
| Max size (in bytes) a client is willing to handle for a
  job result.

| run_directly
| bool
| Indicates whether the user intentionally and directly ran
  this job, or if it was created as a sub-job or by another
  service.
|===
====

.`multiblast_fmt_jobs`
[%collapsible]
====
[cols="1m,1m,4"]
|===
| Column | Type | Purpose

| report_digest
| byte[16]
| Primary key.  Digest of the report configuration.

| job_digest
| byte[16]
| Foreign key to `multiblast_jobs.job_digest`

| status
| varchar(10)
| Last known status for the job.  This value is updated only
  when a client requests info about a job from the service. +
  **WARNING**: This column is for internal service usage and
  cannot be used to accurately derive overall assessments.
  For example, it is a normal case for this field to
  indicate that a job is "queued" when in reality the job
  has completed or failed.

| config
| clob
| Parsed report configuration.

| queue_id
| int(7)
| ID of the job in the Fireworq queue.  This value is
  updated when jobs are re-run.

| created_on
| timestamptz
| Timestamp for the job creation.
|===
====

.`multiblast_users_to_fmt_jobs`
[%collapsible]
====
[cols="1m,1m,4"]
|===
| Column | Type | Purpose

| report_digest
| byte[16]
| Foreign key to `multiblast_fmt_jobs.report_digest`

| user_id
| int(12)
| WDK Site user ID.

| description
| varchar(1024)
| User provided description for the job this record links
  to.
|===
====

== Workflow

=== Blast Jobs

.Basic Blast Workflow
--
image::assets/blast-job.svg[]
--

=== Formatter Jobs

.Basic Formatter Workflow
--
image::assets/format-job.svg[]
--

== TODOS

Describe:
. job hierarchy