$schema: http://json-schema.org/draft-07/schema

title: Base DIAMOND CLI Options

description: |-
  Options common to all DIAMOND CLI tools used by the multi-blast service. 

definitions:
  sensitivity-enum:
    title: Sensitivity
    type: string
    enum:
    - faster
    - fast
    - mid-sensitive
    - shapes-30x10
    - sensitive
    - more-sensitive
    - very-sensitive
    - ultra-sensitive

allOf:
- $ref: ../cli-common/cli-config.yml
- type: object
  properties:
    query:
      type: string

    eValue:
      title: Maximum Expect Value
      description: |-
        Flag: `--evalue | -e`
        
        Maximum e-value to report alignments.
      type: number
      default: 0.001

    maxTargetSeqs:
      title: Maximum Target Sequences
      description: |-
        Flag: `--max-target-seqs` | `-k`
        
        Maximum number of target sequences to report alignments for.
      type: integer
      minimum: 1
      default: 25

    sensitivity:
      title: Aligner Sensitivity
      description: |-
        Configures the aligner sensitivity.
      $ref: '#/definitions/sensitivity-enum'

    masking:
      title: Masking Algorithm
      description: |-
        Flag: `--masking`
        
        Enum values based on the textual masking algorithm option
        representations.
      type: string
      enum:
      - none
      - tantan
      - seg

    compBasedStats:
      title: Composition Based Statistics
      description: |-
        Flag: `--comp-based-stats`
        
        Enum values based on the commonly available DIAMOND CLI option names.
        
        Mapping of option names to CLI inputs:
        
        | Name                         | CLI Input |
        |------------------------------|-----------|
        | disabled                     | 0         |
        | hauser                       | 1         |
        | hauser-and-avg-matrix-adjust | 2         |
        | hauser-and-matrix-adjust     | 3         |
        | matrix-adjust                | 4         |
        
        This list is incomplete, however additional options require a version of
        DIAMOND compiled with those options enabled.
        
        **WARNING**: Option `2` (`"hauser-and-avg-matrix-adjust"`) has been
        marked as deprecated as of DIAMOND v2.1.0 and may be removed or replaced
        in future versions.
      type: string
      enum:
      - disabled
      - hauser
      - hauser-and-avg-matrix-adjust
      - hauser-and-matrix-adjust
      - matrix-adjust

    iterate:
      title: Iterated Search
      description: |-
        Iterated search with increasing sensitivity.
        
        An absent value indicates the option is unused.
        
        This option takes an array of zero or more `sensitivity` options.  An
        empty array is equivalent to an array of the specified target
        sensitivity and all higher sensitivity values.
  
        For example, if `sensitivity` is set to `more-sensitive`, an empty array
        value for `iterate` would be equivalent to:
        
        ```json
        [
          more-sensitive,
          very-sensitive,
          ultra-sensitive
        ]
        ```
      type: array
      items:
        $ref: '#/definitions/sensitivity-enum'
      additionalItems: false
      uniqueItems: true

    reportUnaligned:
      title: Report Unaligned Queries
      description: |-
        Flag: `--unal`
        
        Trinary value represented by `true`, `undefined`, and `false`.
      type: boolean

    outFormat:
      description: |-
        Flag: `--outfmt` | `-f`
        
        Configures the DIAMOND query result output format.
      $ref: './out-format.yml'
